"""R0 item 5: the round-3 preflight checks P1-P7, written to docs/presubmission/round3/PREFLIGHT.md.

Every figure is read from an artifact, a file on disk or the code; none is typed except the plan's own
tables (PLAN Annex 1 and Annex 2 E1/E2), which are written out here only so the artifacts can be
compared with them. Where the two differ, the artifact wins (PLAN, preamble) and the difference is
listed. Each check is PASS or FAIL; any FAIL stops R0 BLOCKED.
Run from the repository root:  $PY docs/presubmission/round3/r0_preflight.py
"""
import hashlib, importlib, json, os, re, subprocess, sys

sys.path.insert(0, "scripts")
sys.path.insert(0, "src")
OUT = "docs/presubmission/round3/PREFLIGHT.md"
J = lambda p: json.load(open(p))
md, verdicts = ["# Round-3 preflight (R0 item 5)\n",
                "Generated by `docs/presubmission/round3/r0_preflight.py`. Each check is PASS or FAIL; any FAIL "
                "stops R0 BLOCKED. Where an artifact and the plan differ, the artifact wins (PLAN, preamble) and "
                "the difference is listed under the check.\n"], {}


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def grep_line(path, pattern, nth=0):
    hits = [i + 1 for i, l in enumerate(open(path, encoding="utf-8")) if re.search(pattern, l)]
    assert len(hits) > nth, (path, pattern, hits)
    return hits[nth]


def pct(x):
    return f"{x:+.1f}"


def ci(c):
    return f"[{c[0]:.1f}, {c[1]:.1f}]"


# ---------------------------------------------------------------- P1 weights
import rwm_data as R  # noqa: E402
paths = R.repo_paths()
ck = paths["ckpt"]
setup_sha = re.search(r'CKPT_SHA256="([0-9a-f]{64})"', open("setup.sh").read()).group(1)
need = {"released checkpoint (setup.sh target)": ck}
for a in ("A", "B"):
    for s in (0, 1, 2):
        for it in (2500, 10000):
            need[f"Arm {a} seed {s}, 10k run, {it:,}"] = f"runs/arm{a}_seed{s}_10k/weights_{it}.pt"
missing = [k for k, p in need.items() if not (os.path.exists(p) and os.path.getsize(p) > 0)]
ck_ok = os.path.exists(ck) and sha(ck) == setup_sha
d1_line = grep_line("scripts/task_d1_threeseed.py", r'runs/arm\{a\}_seed\{s\}_10k/weights_10000\.pt')
twin = []
for a in ("A", "B"):
    for s in (0, 1, 2):
        p1, p2 = f"runs/arm{a}_seed{s}/weights_2500.pt", f"runs/arm{a}_seed{s}_10k/weights_2500.pt"
        twin.append((a, s, os.path.exists(p1) and sha(p1) == sha(p2)))
ab_w = J("results/alignment_by_horizon.json")["weights"]
p1 = not missing and ck_ok
verdicts["P1"] = p1
md += ["## P1 — weights for X2\n",
       f"- The released checkpoint: `../robotic_world_model_lite/assets/models/pretrain_rnn_ens.pt` "
       f"({'present' if os.path.exists(ck) else 'MISSING'}); its SHA-256 {'equals' if ck_ok else 'DIFFERS FROM'} `setup.sh`'s `CKPT_SHA256`.",
       f"- Arm A and Arm B 10k runs, seeds 0-2, `weights_2500.pt` and `weights_10000.pt`: "
       f"{len(need) - 1 - len([m for m in missing if 'Arm' in m])}/{len(need) - 1} present.",
       f"- Arm B's 10k checkpoints: `results/task_d1_threeseed.json` does not record paths; its script names them, "
       f"`runs/arm{{a}}_seed{{s}}_10k/weights_10000.pt` (`scripts/task_d1_threeseed.py:{d1_line}`), so Arm B's are "
       f"`runs/armB_seed{{0,1,2}}_10k/weights_{{2500,10000}}.pt`.",
       f"- `results/alignment_by_horizon.json` scored Arm A at 2,500 from `{ab_w['arm_a_2500']}` (the 2,500-iteration runs), "
       f"not from the 10k runs. Each 10k run's `weights_2500.pt` is byte-identical to its 2,500-iteration run's "
       f"(SHA-256 compared), for Arm A and Arm B, all seeds: "
       f"{'yes' if all(t[2] for t in twin) else 'NO: ' + str([t for t in twin if not t[2]])}. "
       f"So R1's assertion (a) at 2,500 compares the same weights whichever path it loads.",
       f"- Missing or empty: {', '.join(missing) or 'none'}.\n",
       f"**P1: {'PASS' if p1 else 'FAIL'}.**\n"]

# ---------------------------------------------------------------- P2 action timing
A = J("results/alignment_by_horizon.json")
HS = A["horizons"]
# PLAN Annex 2 E2's table: h -> (all ten rel, all ten nrmse, held-out rel, held-out nrmse), each (pct, lo, hi)
PLAN_E2 = {1: ((55.0, 26.3, 92.7), (7.4, -14.8, 87.8), (34.2, 10.6, 75.0), (51.0, 11.8, 88.0)),
           8: ((54.4, 37.5, 82.3), (31.5, 24.7, 68.2), (37.2, 7.9, 95.6), (59.8, 12.4, 97.8)),
           32: ((37.4, 21.3, 65.4), (17.4, 7.7, 47.4), (47.7, 5.8, 131.8), (99.6, 11.9, 170.5)),
           100: ((8.2, -10.4, 24.9), (7.9, -18.9, 32.9), (22.5, 6.3, 41.7), (27.6, 7.6, 40.9)),
           128: ((-8.8, -23.8, 4.9), (-8.3, -30.3, 5.8), (20.3, 7.0, 35.7), (21.6, 5.9, 28.7)),
           368: ((-4.6, -13.4, 3.2), (-2.1, -10.0, 3.9), (7.9, 3.1, 13.0), (6.6, 1.0, 8.0))}
CELLS = (("all_ten_n20", "rel_l1"), ("all_ten_n20", "nrmse_form1"), ("held_out_n4", "rel_l1"), ("held_out_n4", "nrmse_form1"))
rs = A["released"]["summary"]
diffs2 = []
md += ["## P2 — the action-timing figures\n",
       "`results/alignment_by_horizon.json` `released.summary`: the released checkpoint's % change in error with the stale "
       "action (offset 0 against offset 1), point and 95% interval. Arenas: `all_ten_n20` (20 independent trajectories, "
       f"{A['bootstrap']['all_ten_n20']}) and `held_out_n4` (4, {A['bootstrap']['held_out_n4']}).\n",
       "| h | all ten (20), relative-L1 | all ten (20), nRMSE (form 1, pooled) | held-out pair (4), relative-L1 | held-out pair (4), nRMSE (form 1, pooled) | equals Annex 2 E2 at 1 d.p. |",
       "|---:|---|---|---|---|---|"]
for h in HS:
    cells, ok = [], True
    for k, (ar, met) in enumerate(CELLS):
        x = rs[ar][str(h)][met]
        cells.append(f"{pct(x['pct'])} {ci(x['ci95_pct'])}")
        got = (round(x["pct"], 1), round(x["ci95_pct"][0], 1), round(x["ci95_pct"][1], 1))
        if got != PLAN_E2[h][k]:
            ok = False
            diffs2.append(f"h = {h}, {ar} {met}: artifact {got}, plan {PLAN_E2[h][k]}")
    md.append(f"| {h} | " + " | ".join(cells) + f" | {'yes' if ok else 'NO'} |")
res = {ar: {str(h): {m: (lambda c: c[0] > 0 or c[1] < 0)(rs[ar][str(h)][m]["ci95_pct"]) for m in ("rel_l1", "nrmse_form1")}
            for h in HS} for ar in rs}
md += ["",
       "Resolved (interval excludes zero), read from the intervals above: "
       + "; ".join(f"{ar}: " + ", ".join(f"h = {h} " + "/".join(("rel" if m == 'rel_l1' else "nRMSE") + (" resolved" if res[ar][str(h)][m] else " n.r.")
                                                                for m in ("rel_l1", "nrmse_form1")) for h in HS) for ar in ("all_ten_n20", "held_out_n4"))
       + " (n.r. = interval includes zero). nRMSE throughout is form 1 (`nrmse_form1`, pooled); the artifact also holds `nrmse_curve`, which the paper does not use.\n"]
# Arm A
md += ["**Arm A** (`arm_a`), held-out pair (4), % change with the stale action; per seed with its exact 256-resample "
       "interval, and the three-seed mean (`summary_three_seed_mean_pct`, a point value):\n",
       "| checkpoint | h | metric | seed 0 | seed 1 | seed 2 | three-seed mean |", "|---|---:|---|---|---|---|---:|"]
for it in ("2500", "10000"):
    blk = A["arm_a"][it]
    for h in HS:
        for m in ("rel_l1", "nrmse_form1"):
            ps = [blk["summary_per_seed"][s][str(h)][m] for s in ("0", "1", "2")]
            md.append(f"| {int(it):,} | {h} | {'relative-L1' if m == 'rel_l1' else 'nRMSE'} | "
                      + " | ".join(f"{x['pct']:+.2f} [{x['ci95_pct'][0]:+.2f}, {x['ci95_pct'][1]:+.2f}]" for x in ps)
                      + f" | {blk['summary_three_seed_mean_pct'][str(h)][m]:+.2f} |")
a10 = A["arm_a"]["10000"]["summary_three_seed_mean_pct"]
plan_a = {"1": -0.22, "368": 0.15}
for h, v in plan_a.items():
    if round(a10[h]["rel_l1"], 2) != v:
        diffs2.append(f"Arm A 10,000, h = {h}, relative-L1 three-seed mean: artifact {a10[h]['rel_l1']:+.2f}, Annex 1 {v:+.2f}")
maxabs = max(abs(A["arm_a"][it]["summary_three_seed_mean_pct"][str(h)][m]) for it in ("2500", "10000") for h in HS for m in ("rel_l1", "nrmse_form1"))
md += ["",
       f"Annex 1 quotes Arm A at 10,000 as −0.22% at h = 1 and +0.15% at h = 368 (relative-L1, three-seed mean); the artifact "
       f"gives {a10['1']['rel_l1']:+.2f}% and {a10['368']['rel_l1']:+.2f}%. The largest three-seed mean |change| over both checkpoints, "
       f"every horizon and both metrics is {maxabs:.2f}%. Arm A has no all-ten-episodes arena in this artifact.\n",
       f"Differences from the plan: {'; '.join(diffs2) if diffs2 else 'none'}.\n"]
p2_released = not diffs2 and A["released"]["reproduces_alignment_defect_ci_at_h368"]["held_out_n4"]["reproduced"] \
    and A["released"]["reproduces_alignment_defect_ci_at_h368"]["all_ten_n20"]["reproduced"]
# The Arm A half: r0_defect_check.py, run before this script, tests whether alignment_defect_ci.rollout
# scored our own models correctly (causal pairing only; no stale-pairing figure and no X2 reading).
DC = J("docs/presubmission/round3/r0_defect_check.json")
l_unpack = grep_line("scripts/alignment_defect_ci.py", r"pred, \*_ = model\.rollout\(st, ac, E\.START_STEP, action_offset=offset\)")
l_rwm_ret = grep_line("src/rwm_model.py", r"^\s+return pred$")
l_ref_ret = grep_line("src/score_reference.py", r"^\s+return pred, alea, epis, contacts, terms$")
r1 = next(r for r in DC["rows"] if r["iterations"] == 10000 and r["arena"] == "held_out" and r["h"] == 1)
defect = DC["verdict"] == "DEFECT CONFIRMED"
md += ["### P2, the Arm A half: the committed figures come from a defective rollout\n",
       f"`scripts/alignment_defect_ci.py:{l_unpack}` unpacks `pred, *_ = model.rollout(...)`. The released checkpoint's "
       f"`ReferenceRWM.rollout` returns a tuple (`src/score_reference.py:{l_ref_ret}`), so that takes the prediction. Our models' "
       f"`RWMEnsemble.rollout` returns the prediction tensor itself (`src/rwm_model.py:{l_rwm_ret}`), shape (n, 400, 45), so the "
       f"same line takes its first trajectory, shape {tuple(DC['rows'][0]['as_is_pred_shape'])}, and numpy broadcasts that one "
       "forecast against every trajectory's truth. `scripts/alignment_by_horizon.py` scored Arm A through exactly this path.\n",
       "`docs/presubmission/round3/r0_defect_check.py` (output `round3/r0_defect_check.json`) tests it on the causal pairing "
       "only, so it computes no stale-pairing figure and no rule-X2 reading. Arm A seeds 0-2, at 2,500 and 10,000, both arenas, "
       "h = 1, 8, 32, 100, three-seed mean relative-L1:",
       f"- through the committed path, the error is {min(r['as_is'] for r in DC['rows']):.3f} to {max(r['as_is'] for r in DC['rows']):.3f} "
       f"at every cell, against `mn_compute_matched.json`'s {min(r['committed'] for r in DC['rows']):.3f} to "
       f"{max(r['committed'] for r in DC['rows']):.3f} (largest difference {DC['max_abs_diff_from_committed']['as_is']:.3f}); "
       f"for example 10,000 iterations, held-out pair, h = 1: {r1['as_is']:.4f} against {r1['committed']:.4f};",
       f"- with the tensor taken whole, the same imported functions reproduce `mn_compute_matched.json` at every cell to "
       f"{DC['max_abs_diff_from_committed']['unpacked']:.1e};",
       f"- the committed path reproduces `alignment_by_horizon.json`'s own Arm A offset-1 per-trajectory errors at h = 1 to 1e-9: "
       f"{'yes' if DC['as_is_reproduces_alignment_by_horizon_arm_a_offset1_h1_per_trajectory'] else 'NO'}.\n",
       f"Verdict: **{DC['verdict']}**. Every Arm A figure in `alignment_by_horizon.json` (`arm_a`, both checkpoints, all horizons, "
       "both metrics) compares one trajectory's forecast with four trajectories' truths, so three of the four units are "
       "unrelated pairs and any effect of the action is diluted by the mismatch. Annex 1's \"−0.22% at h = 1 and +0.15% at "
       "h = 368\", ledger R-76's \"our own checkpoints barely feel it\", §7.2's sentence (keys `stale_armA_rel_h1`, "
       "`stale_armA_rel_h368`) and the model card's action-convention line all rest on it. The released checkpoint's figures "
       "are unaffected. How Arm A responds to the stale action is unknown.\n"]
p2 = p2_released and not defect
verdicts["P2"] = p2
md += [f"**P2: {'PASS' if p2 else 'FAIL'}.** The released checkpoint's half: {'PASS' if p2_released else 'FAIL'} (it matches "
       "Annex 2 E2, and the artifact records that it reproduces `alignment_defect_ci.json` at h = 368 in both arenas to 1e-9). "
       f"The Arm A half: {'FAIL, the defect above' if defect else 'PASS'}. R0 stops BLOCKED "
       "(`DECISIONS.md#R0-arm-a-rollout-defect`).\n"]

# ---------------------------------------------------------------- P3 equal compute
MC = J("results/mn_compute_matched.json")
P3 = MC["part3_readings"]
cfg_name = {"M32_N32": "(32, 32)", "M32_N16": "(32, 16)", "M8_N8": "(8, 8)", "M2_N8": "(2, 8)"}
# PLAN Annex 2 E1: (config, centre iters) -> compute ratio, then 4 cells (D, lo, hi or None, bold)
PLAN_E1 = {("M32_N32", 5000): (1.11, [(-0.0918, -0.1901, 0.0065, False), (0.0454, 0.0356, 0.0563, True), (-0.2031, -0.5033, -0.0275, True), (0.0084, -0.0006, 0.0161, False)]),
           ("M32_N32", 10000): (2.21, [(-0.0352, -0.1142, 0.0438, False), (0.0920, 0.0770, 0.1068, True), (-0.0594, -0.1903, 0.0340, False), (0.0560, 0.0483, 0.0639, True)]),
           ("M32_N16", 5000): (1.48, [(-0.0723, -0.1466, 0.0020, False), (0.0400, 0.0326, 0.0481, True), (-0.1671, -0.4301, -0.0117, True), (0.0142, 0.0068, 0.0205, True)]),
           ("M8_N8", 2500): (2.50, [(-0.0755, None, None, True), (-0.0142, None, None, True), (-0.1004, None, None, True), (-0.0208, None, None, True)]),
           ("M8_N8", 10000): (9.98, [(0.0343, -0.0198, 0.0719, False), (0.1162, None, None, True), (0.1270, 0.0987, 0.1589, True), (0.1414, None, None, True)]),
           ("M2_N8", 2500): (3.78, [(-0.1274, None, None, True), (-0.0219, None, None, True), (-0.1139, None, None, True), (-0.0219, None, None, True)]),
           ("M2_N8", 10000): (15.1, [(-0.0176, None, None, False), (0.1085, None, None, True), (0.1135, 0.0983, 0.1357, True), (0.1403, None, None, True)])}
CC = (("h100", "held_out"), ("h100", "in_sample"), ("h368", "held_out"), ("h368", "in_sample"))
diffs3, rounding3 = [], []
md += ["## P3 — the equal-compute readings\n",
       f"`results/mn_compute_matched.json` `part3_readings`. Statistic: {P3['statistic']}. Intervals: {P3['interval']}. "
       "The compute ratio is the centre's total compute ÷ the configuration's (= 1 / `config_total_compute_over_centre_at_k`), "
       "as Annex 2 E1 defines it; cost per iteration is `config_cost_per_iter_over_centre`. **Bold** = the interval excludes zero.\n",
       "| config (cost/iter ÷ centre's) | centre trained to | compute ratio | h=100 held-out (4) | h=100 in-sample (16) | h=368 held-out (4) | h=368 in-sample (16) | in Annex 2 E1 | equals it |",
       "|---|---:|---:|---|---|---|---|---|---|"]
order = sorted(P3["readings"].items(), key=lambda kv: (list(cfg_name).index(kv[1]["config"]), kv[1]["centre_iterations"]))
for key, r in order:
    cr = r["compute_ratios"]
    ratio = 1 / cr["config_total_compute_over_centre_at_k"]
    cells, plan_cells = [], PLAN_E1.get((r["config"], r["centre_iterations"]))
    ok = True
    for k, (h, ar) in enumerate(CC):
        x = r[h][ar]
        ex = x["ci95"][0] > 0 or x["ci95"][1] < 0
        s = f"{x['D']:+.4f} [{x['ci95'][0]:+.4f}, {x['ci95'][1]:+.4f}]"
        cells.append(f"**{s}**" if ex else s)
        if plan_cells:
            pD, plo, phi, pb = plan_cells[1][k]
            if round(x["D"], 4) != pD or (plo is not None and (round(x["ci95"][0], 4), round(x["ci95"][1], 4)) != (plo, phi)) or ex != pb:
                ok = False
                diffs3.append(f"{key} {h} {ar}: artifact {x['D']:+.4f} {x['ci95']} excl0={ex}; plan {plan_cells[1][k]}")
    if plan_cells and round(ratio, 2 if ratio < 10 else 1) != plan_cells[0]:
        # the plan types the ratio at 2 d.p. (1 d.p. from 10); a difference of less than one unit in
        # that place is the plan's rounding (truncation), logged, and the artifact's value stands
        if abs(ratio - plan_cells[0]) < (0.01 if ratio < 10 else 0.1):
            rounding3.append(f"{key}: the plan prints the compute ratio as {plan_cells[0]}; the artifact gives "
                             f"{ratio:.4f}, which rounds to {round(ratio, 2 if ratio < 10 else 1)}")
        else:
            ok = False
            diffs3.append(f"{key} compute ratio: artifact {ratio:.4f}, plan {plan_cells[0]}")
    md.append(f"| {cfg_name[r['config']]} ({cr['config_cost_per_iter_over_centre']:.2f}) | {r['centre_iterations']:,} | {ratio:.2f} | "
              + " | ".join(cells) + f" | {'yes' if plan_cells else 'no'} | {('yes' if ok else 'NO') if plan_cells else '—'} |")
md += ["", f"Rows: {len(P3['readings'])} (Annex 2 E1 prints {len(PLAN_E1)} of them). Differences from the plan, at 4 d.p.: "
       f"{'; '.join(diffs3) if diffs3 else 'none'}. Rounding in the plan's text (logged; the artifact wins): "
       f"{'; '.join(rounding3) if rounding3 else 'none'}.\n"]
p3 = len(P3["readings"]) == 12 and not diffs3
verdicts["P3"] = p3
md += [f"**P3: {'PASS' if p3 else 'FAIL'}.**\n"]

# ---------------------------------------------------------------- P4 changed nRMSE readings
PN = J("results/pooled_nrmse_alongside.json")
want = ["M-75 in_sample|nrmse_h1", "M-76 in_sample|nrmse_h100"]
p4 = PN["readings_whose_result_changed"] == want
vb = "scripts/verdict_baselines.py"
l_stat = grep_line(vb, r"statistic\s+D_b = mean over")
l_pb = grep_line(vb, r"^def per_baseline")
md += ["## P4 — the changed nRMSE readings\n",
       f"`readings_whose_result_changed` = {PN['readings_whose_result_changed']}; required exactly {want}: {'yes' if p4 else 'NO'}.\n",
       f"Sign of D: `D_b = 3-seed mean err_b − 3-seed mean err_RWM`, so **positive favours RWM** (`{vb}:{l_stat}-{l_stat + 1}`); "
       f"`per_baseline` names a rejected D_b > 0 \"RWM BETTER\" and a rejected D_b < 0 \"BASELINE BETTER\" (`{vb}:{l_pb}-{l_pb + 4}`).\n",
       "| reading | baseline | committed D [95%] | rejected | pooled D [95%] | rejected |", "|---|---|---|---|---|---|"]
for w in want:
    rule, rd = w.split(" ", 1)
    r = PN["readings"][rule][rd]
    for b in r["committed"]["per_key"]:
        c, p = r["committed"]["per_key"][b], r["pooled"]["per_key"][b]
        md.append(f"| {w} | `{b}` | {c['D']:+.4f} [{c['ci95'][0]:+.4f}, {c['ci95'][1]:+.4f}] | {c['rejected']} | "
                  f"{p['D']:+.4f} [{p['ci95'][0]:+.4f}, {p['ci95'][1]:+.4f}] | {p['rejected']} |")
    md.append(f"| {w} | **result** | {r['committed']['result']} | | {r['pooled']['result']} | |")
md += ["", "Annex 2 E4's figures (teacher-forced h = 1: MLP −0.160 [−0.286, −0.002], RSSM −0.186 [−0.328, −0.013], transformer "
       "−0.052 [−0.089, −0.005]; autoregressive h = 100: MLP +0.017 [−0.017, +0.044]) agree with the pooled column at 3 d.p.: "]
e4 = {("M-75", "mlp_tf_s7"): (-0.160, -0.286, -0.002), ("M-75", "rssm_tf_s7"): (-0.186, -0.328, -0.013),
      ("M-75", "transformer_tf_s7"): (-0.052, -0.089, -0.005), ("M-76", "mlp_ar_s7"): (0.017, -0.017, 0.044)}
bad4 = []
for (rule, b), v in e4.items():
    rd = "in_sample|nrmse_h1" if rule == "M-75" else "in_sample|nrmse_h100"
    p = PN["readings"][rule][rd]["pooled"]["per_key"][b]
    got = (round(p["D"], 3), round(p["ci95"][0], 3), round(p["ci95"][1], 3))
    if got != v:
        bad4.append(f"{rule} {b}: artifact {got}, plan {v}")
md[-1] += ("yes." if not bad4 else "NO: " + "; ".join(bad4)) + " Annex 3 A5b writes the teacher-forced leads unsigned, as how far each baseline is ahead.\n"
p4 = p4 and not bad4
verdicts["P4"] = p4
md += [f"**P4: {'PASS' if p4 else 'FAIL'}.**\n"]

# ---------------------------------------------------------------- P5 the original's printed hours
spec_line = grep_line("docs/presubmission/ORIGINAL_SPECS.md", r"^\| a\.5 ")
spec = open("docs/presubmission/ORIGINAL_SPECS.md", encoding="utf-8").read().splitlines()[spec_line - 1]
hours = re.search(r"Printed training hours \(right heatmap\), M = 32:\*\* (.+?)\. \|", spec).group(1)
hv = [float(x) for x in re.findall(r"→ (\d+\.\d+)", hours)]
found = []


def walk(o, path, f):
    if isinstance(o, dict):
        for k, v in o.items():
            walk(v, path + [str(k)], f)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            walk(v, path + [str(i)], f)
    elif isinstance(o, (int, float)) and not isinstance(o, bool):
        if any(abs(o - x) < 1e-12 for x in hv):
            found.append((f, ".".join(path), o))
    elif isinstance(o, str) and re.search(r"training hours|\b2\.27\b.*\b1\.07\b|\b1\.07\b.*\b2\.27\b", o):
        found.append((f, ".".join(path), o[:80]))


for f in sorted(os.listdir("results")):
    if f.endswith(".json"):
        try:
            walk(J("results/" + f), [], f)
        except Exception:
            pass
hrs_art = [x for x in found if not isinstance(x[2], (int, float)) or True]
held = [x for x in found if isinstance(x[2], str)]
numeric = [x for x in found if not isinstance(x[2], str)]
mo = next(c for c in J("results/original_paper_figures.json")["claims"] if c["key"] == "mn_optimal")
held_vals = any(re.search(r"\b1\.07\b|\b2\.27\b", v) for _, _, v in held)
held_note = ("None holds a value: the two in `comparative_claims.json` are whole copies of the paper template inside "
             "self-test corruption records (the template names Figure 6's training hours in Appendix D without printing one), "
             "and `original_paper_figures.json`'s describes Figure 6." if held and not held_vals else
             ("AT LEAST ONE HOLDS A VALUE; read it." if held else ""))
md += ["## P5 — the original's printed training hours\n",
       f"`docs/presubmission/ORIGINAL_SPECS.md:{spec_line}` (row a.5) lists them: {hours}.\n",
       f"- A string in any `results/*.json` naming training hours or the 1.07/2.27 pair: "
       f"{'; '.join(f'`{a}` {b}' for a, b, _ in held) or 'none'}. {held_note}",
       f"- A numeric field equal to one of the five printed hours ({', '.join(str(x) for x in hv)}), anywhere in `results/*.json`: "
       f"{len(numeric)} (coincidences, not the hours, if any: {', '.join(sorted(set(a for a, _, _ in numeric))) or 'none'}).",
       f"- `results/original_paper_figures.json`'s `mn_optimal` entry has the fields {sorted(mo.keys())}; none holds the hours.",
       "\n**P5: none.** No `results/` artifact holds the original's printed training hours; R2 adds them (Annex 2 E1) to "
       "`results/original_paper_figures.json`'s `mn_optimal` entry through its generator. (P5 is a record, not a pass/fail "
       "condition.)\n"]
verdicts["P5"] = True

# ---------------------------------------------------------------- P6 rules and labels
G = J("results/appendix_g_rules.json")
F = J("results/paper_figures.json")
fig_rows = list(F["fig4"].keys())
pos = sum(1 for v in F["fig4"].values() if v["lead_hours"] > 0)
l_fig = grep_line("scripts/paper_figures.py", r"^def fig4_timeline")
l_cases = grep_line("scripts/paper_figures.py", r"^\s+CASES = \[")
l_map = grep_line("scripts/build_paper.py", r"^\s+_cmap = AB\.COMMIT_LABELS")
l_imp = grep_line("scripts/build_paper.py", r"^\s+import make_anon_bundle as AB")
l_cl = grep_line("scripts/make_anon_bundle.py", r"^COMMIT_LABELS = commit_label_map\(\)")
l_lab = grep_line("scripts/make_anon_bundle.py", r"^def commit_label_map")
l_labf = grep_line("scripts/make_anon_bundle.py", r'return \{h: f"C\{i:03d\}"')
l_apply = grep_line("scripts/build_paper.py", r"_sub_text = AB\.apply_commit_labels")
l_rc = grep_line("scripts/appendix_g_rules.py", r'"rule_commit": commits\.get\(key')
l_self = grep_line("scripts/appendix_g_rules.py", r'"git", "log", "--format=%ct", "-S"')
l_dash = grep_line("scripts/paper_numbers.py", r'if r\["rule_commit"\] else "—"')
dash = [r["id"] for r in G["rules"] if not r["rule_commit"]]
fig_ids = {r["id"] for r in G["rules"] if r["lead_source"] == "Figure 4"}
md += ["## P6 — rules and labels\n",
       f"- Rules in `results/appendix_g_rules.json`: **{G['n_rules']}** (`n_rules`; {len(G['rules'])} rows; {G['n_with_lead_time']} with a lead time).",
       f"- Figure 1 (named \"Figure 4\" in the code and in `appendix_g_rules.json`'s `lead_source`: `paper_fig4_prereg_timeline` renders as the paper's Figure 1) plots **{len(fig_rows)}** bars (`results/paper_figures.json` `fig4`): {', '.join(fig_rows)}. {pos} are positive and "
       f"{len(fig_rows) - pos} is not. They are a fixed list, `CASES` at `scripts/paper_figures.py:{l_cases}`, inside the generator "
       f"`fig4_timeline()` at `scripts/paper_figures.py:{l_fig}`. Two of the bars are not Appendix E rows by ID: \"flip pattern "
       f"interpretation\" (M-16's annotation) and \"Task 3 duplication rule\" (withdrawn by S-12). Appendix E's rows that take their "
       f"lead time from Figure 1: {', '.join(sorted(fig_ids))}.",
       f"- Anonymous commit labels (`C001`, `C002`, … in commit-date order, e.g. `C016`) are built by `commit_label_map()` at "
       f"`scripts/make_anon_bundle.py:{l_lab}` (the label format at `:{l_labf}`); the map `COMMIT_LABELS` is assembled at "
       f"`scripts/make_anon_bundle.py:{l_cl}-{l_cl + 2}` from it plus the Hugging Face and pre-purge maps. The paper build imports "
       f"the module at `scripts/build_paper.py:{l_imp}`, reads the map at `:{l_map}` and applies it to the LaTeX at `:{l_apply}`. "
       "PAPER.md keeps real hashes.",
       f"- Appendix E's commit column shows \"—\" for {len(dash)} rules: {', '.join(dash)}. The cell is \"—\" whenever "
       f"`rule_commit` is empty (`scripts/paper_numbers.py:{l_dash}`), and `rule_commit` is filled only from Figure 1's record "
       f"(`scripts/appendix_g_rules.py:{l_rc}`, `commits.get(key, …)`). For the rules not on Figure 1, the generator computes the "
       f"lead time itself from git, finding the commit that introduced the rule's ledger heading (`git log -S`, "
       f"`scripts/appendix_g_rules.py:{l_self}`), but does not store that commit. No deliberate reason is recorded in the code or the "
       f"caption; the blank is an omission of the generator.\n",
       "**P6: PASS** (a record).\n"]
verdicts["P6"] = True

# ---------------------------------------------------------------- P7 action pairing in code
l_at = grep_line("scripts/alignment_by_horizon.py", r"^def at_horizon")
l_rel = grep_line("scripts/alignment_by_horizon.py", r"at_horizon\(h, ref, data, cfg, scale, mk\(s4\)")
l_rel20 = grep_line("scripts/alignment_by_horizon.py", r"at_horizon\(h, ref, data, cfg, scale, mk\(s20\)")
l_arm = grep_line("scripts/alignment_by_horizon.py", r"at_horizon\(h, model, data, cfg, scale, mk\(s4\)")
l_adc_ro = grep_line("scripts/alignment_defect_ci.py", r"model\.rollout\(st, ac, E\.START_STEP, action_offset=offset\)")
l_adc_ar = grep_line("scripts/alignment_defect_ci.py", r"runs = \{o: rollout\(model, data, cfg, idx, o\) for o in \(0, 1\)\}")
l_ref = grep_line("src/score_reference.py", r"^\s+def rollout\(self, state, action, start_step=32, action_offset=0")
l_ref_a = grep_line("src/score_reference.py", r"a_in = action\[:, i - start_step \+ action_offset:i \+ action_offset\]", 2)
l_ref_b = grep_line("src/score_reference.py", r"a_in = action\[:, i - 1 \+ action_offset:i \+ action_offset\]", 2)
l_rwm = grep_line("src/rwm_model.py", r"^\s+def rollout\(self, state, action, start_step, action_offset=1\)")
l_rwm_b = grep_line("src/rwm_model.py", r"a_in = action\[:, i - 1 \+ action_offset:i \+ action_offset\]", 1)
l_rwm_a = grep_line("src/rwm_model.py", r"a_in = action\[:, i - start_step \+ action_offset:i \+ action_offset\]", 1)
try:
    sys.argv = ["mn_sweep_eval"]
    MSE = importlib.import_module("mn_sweep_eval")
    imp_ok, arena_line = callable(MSE.arena), grep_line("scripts/mn_sweep_eval.py", r"^def arena\(")
    imp_note = f"imports cleanly with `scripts/` and `src/` on the path; its in-sample arena builder is `arena(ep, episodes, m_max)` at `scripts/mn_sweep_eval.py:{arena_line}`"
except Exception as ex:  # noqa: BLE001
    imp_ok, imp_note = False, f"import FAILED: {ex!r}"
p7 = imp_ok
verdicts["P7"] = p7
md += ["## P7 — action pairing in code\n",
       f"- `scripts/alignment_by_horizon.py` never names `action_offset` itself. It calls `alignment_defect_ci.arena()` through "
       f"`at_horizon()` (`scripts/alignment_by_horizon.py:{l_at}`): for the released checkpoint at `:{l_rel}` (held-out pair) and "
       f"`:{l_rel20}` (all ten episodes), and for Arm A at `:{l_arm}` (held-out pair only).",
       f"- `alignment_defect_ci.arena()` runs both pairings, `for o in (0, 1)` (`scripts/alignment_defect_ci.py:{l_adc_ar}`), and "
       f"`alignment_defect_ci.rollout()` passes the offset to the model, `model.rollout(st, ac, E.START_STEP, action_offset=offset)` "
       f"(`scripts/alignment_defect_ci.py:{l_adc_ro}`). This is where the offset is applied, for both models.",
       f"- The slicing itself: the released checkpoint's `ReferenceRWM.rollout` (`src/score_reference.py:{l_ref}`; default offset 0) "
       f"at `:{l_ref_a}` (first forecast step, the whole history window) and `:{l_ref_b}` (later steps); Arm A's `RWMEnsemble.rollout` "
       f"(`src/rwm_model.py:{l_rwm}`; default offset 1) at `:{l_rwm_a}` and `:{l_rwm_b}`. Both use the same expressions: "
       "the first forecast step i = start_step reads `action[:, i − start_step + offset : i + offset]`, later steps read "
       "`action[:, i − 1 + offset : i + offset]`. (R1 decides from these which rows the forecast steps read; not recorded as a finding here.)",
       f"- `scripts/mn_sweep_eval.py` {imp_note}.\n",
       f"**P7: {'PASS' if p7 else 'FAIL'}.**\n"]

md += ["## Summary\n", " ".join(f"{k}: {'PASS' if v else 'FAIL'}." for k, v in verdicts.items())
       + " (P5 and P6 are records.)\n"]
open(OUT, "w").write("\n".join(md) + "\n")
print(" ".join(f"{k}:{'PASS' if v else 'FAIL'}" for k, v in verdicts.items()))
print("P2 diffs:", diffs2)
print("P3 diffs:", diffs3)
print("P4 bad:", bad4)
sys.exit(0 if all(verdicts.values()) else 1)
