"""F0 item 5: the round-4 preflight checks PF1-PF9, written to docs/presubmission/round4/PREFLIGHT.md.

Every figure and line number is read from an artifact, a file on disk or the code; none is typed. Line
numbers are found by searching each file for the code they cite (`at()`), so they move with the code.
Each check is PASS or FAIL; any FAIL stops F0 BLOCKED, except PF4, which only records (PLAN F0 item 5).
Where an artifact and the plan differ, the artifact wins (PLAN, preamble) and the difference is listed.
Nothing here trains, and nothing rolls a model out: the only computations are parameter counts of freshly
built (untrained) baselines and a recomputation of committed bootstrap intervals from committed
per-trajectory values. Python 3.11: no backslash or double quote inside an f-string's braces, so every
line number is computed into a variable first.
Run from the repository root:  $PY docs/presubmission/round4/f0_preflight.py
"""
import hashlib, importlib, json, os, re, shutil, subprocess, sys

import numpy as np

sys.path.insert(0, "scripts")
sys.path.insert(0, "src")
OUT = "docs/presubmission/round4/PREFLIGHT.md"
LITE = "../robotic_world_model_lite"
J = lambda p: json.load(open(p))
md = ["# Round-4 preflight (F0 item 5)\n",
      "Generated by `docs/presubmission/round4/f0_preflight.py`. Each check is PASS or FAIL; any FAIL stops F0 "
      "`BLOCKED`, except PF4, which only records. Line numbers are found by searching the cited file for the cited "
      "code, never typed. Where an artifact and the plan differ, the artifact wins (PLAN, preamble) and the "
      "difference is listed under the check. Upstream paths are relative to the pinned checkouts beside the "
      "repository: `lite` = `robotic_world_model_lite` (13a798e9), `rsl_rl_rwm` (18eebcdd).\n"]
verdicts = {}


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def at(path, needle, nth=0):
    """1-based line of the nth line holding `needle`, a plain substring; a leading '^' anchors it at the line start."""
    lines = open(path, encoding="utf-8").read().split("\n")
    if needle.startswith("^"):
        hits = [i + 1 for i, l in enumerate(lines) if l.startswith(needle[1:])]
    else:
        hits = [i + 1 for i, l in enumerate(lines) if needle in l]
    assert len(hits) > nth, (path, needle, hits)
    return hits[nth]


def rel(p):
    return os.path.relpath(p) if not p.startswith("..") else p


# ================================================================ PF1 weights
import rwm_data as R  # noqa: E402
paths = R.repo_paths()
ck = paths["ckpt"]
setup_sha = re.search(r'CKPT_SHA256="([0-9a-f]{64})"', open("setup.sh").read()).group(1)
SW, BE = J("results/mn_sweep_eval.json"), J("results/baselines_eval.json")
groups, sha_checks = {}, []
groups["Arm A and Arm B at 2,500 iterations, held-out pair {1, 8}, seeds 0-2"] = \
    [f"runs/arm{a}_seed{s}/weights_2500.pt" for a in "AB" for s in (0, 1, 2)]
groups["Arm A and Arm B at 10,000 iterations, seeds 0-2"] = \
    [f"runs/arm{a}_seed{s}_10k/weights_10000.pt" for a in "AB" for s in (0, 1, 2)]
sweep = []
for c, v in SW["configs"].items():
    for s, r in v["seeds"].items():
        sweep.append(r["weights"]); sha_checks.append(("sweep " + c, r["weights"], r["weights_sha256"]))
groups[f"the {len(SW['configs'])} sweep configurations at {SW['checkpoint_iterations']:,} iterations, 3 seeds each "
       f"(`results/mn_sweep_eval.json`; the centre M32_N8 is Arm A's 2,500-iteration run)"] = sweep
bl = []
fams = [k for k in BE["configs"] if k != "rwm"]
for k in fams:
    for s, r in BE["configs"][k]["seeds"].items():
        bl.append(r["weights"]); sha_checks.append(("baseline " + k, r["weights"], r["weights_sha256"]))
groups[f"the {len(fams)} baseline families at {BE['checkpoint_iterations']:,} iterations, 3 seeds each "
       f"(`results/baselines_eval.json`: {', '.join(fams)})"] = bl
groups["Arm A's three ensemble-5 arms (seeds 0-2, 2,500 iterations)"] = [f"runs/armA_seed{s}_ens5/weights_2500.pt" for s in (0, 1, 2)]
missing = {g: [p for p in ps if not (os.path.exists(p) and os.path.getsize(p) > 0)] for g, ps in groups.items()}
sha_bad = [(lab, p) for lab, p, h in sha_checks if os.path.exists(p) and sha(p) != h]
ck_ok = os.path.exists(ck) and sha(ck) == setup_sha
twin = [(a, s, sha(f"runs/arm{a}_seed{s}/weights_2500.pt") == sha(f"runs/arm{a}_seed{s}_10k/weights_2500.pt"))
        for a in "AB" for s in (0, 1, 2)]
X1 = {"setup": at("setup.sh", "CKPT_SHA256=")}
md += ["## PF1 — weights\n",
       "| Set | Paths | Present and non-empty |", "|---|---|---|"]
for g, ps in groups.items():
    seeded = sorted(set(re.sub(r"seed\d", "seed{s}", p) for p in ps))
    pat = []
    for x in seeded:
        if re.search(r"armA_", x) and x.replace("armA_", "armB_") in seeded:
            pat.append(x.replace("armA_", "arm{A,B}_"))
        elif not (re.search(r"armB_", x) and x.replace("armB_", "armA_") in seeded):
            pat.append(x)
    md.append(f"| {g} | {', '.join('`' + x + '`' for x in pat)} | {len(ps) - len(missing[g])}/{len(ps)} |")
md += [f"| the released checkpoint | `{rel(ck)}` | {'1/1' if os.path.exists(ck) else '0/1'} |", "",
       f"- The released checkpoint's SHA-256 {'equals' if ck_ok else 'DIFFERS FROM'} `setup.sh`'s `CKPT_SHA256` (`setup.sh:{X1['setup']}`).",
       f"- Every sweep and baseline weight file's SHA-256 equals the one its evaluation artifact recorded "
       f"({len(sha_checks)} files): {'yes' if not sha_bad else 'NO: ' + str(sha_bad)}.",
       f"- Each 10k run's `weights_2500.pt` is byte-identical to its 2,500-iteration run's, Arm A and Arm B, all seeds: "
       f"{'yes' if all(t[2] for t in twin) else 'NO: ' + str([t for t in twin if not t[2]])}. So fold {{1, 8}} at 2,500 "
       f"is the same weights whichever path X3 loads."]

# --- which artifact holds Arm B's 2,500-iteration held-out relative-L1 at every horizon
HS = SW["horizons"]
H2H = J("results/head_to_head_accuracy.json")
hb = H2H["rows"]["armB"]
h2h_h = [int(h) for h in hb["cells"]]
AS = J("results/action_sensitivity.json")
as_h = sorted({int(k.rsplit("|h", 1)[1]) for k in AS["per_seed"] if k.startswith("arm_b_2500|seed0|held_out_n4|")})
as_seed = {(s, h): float(np.mean(AS["per_seed"][f"arm_b_2500|seed{s}|held_out_n4|h{h}"]["I0_per_trajectory_err"]))
           for s in (0, 1, 2) for h in as_h}
h2h_seed = {(s, int(h)): hb["per_model"][f"armB_teacher_forced_seed{s}"][h]["l1"]
            for s in (0, 1, 2) for h in hb["per_model"]["armB_teacher_forced_seed0"]}
shared = sorted(set(h2h_h) & set(as_h))
agree = max(abs(as_seed[(s, h)] - h2h_seed[(s, h)]) for s in (0, 1, 2) for h in shared)
MC = J("results/mn_compute_matched.json")["part2_centre_at_more_compute"]
mc_a = MC["three_seed_mean_l1"]["2500"]["held_out"]
a_h = list(H2H["rows"]["armA"]["cells"])
a_agree = max(abs(H2H["rows"]["armA"]["cells"][h]["l1"] - mc_a[h]) for h in a_h)
covered = sorted(set(h2h_h) | set(as_h))
uncovered = [h for h in HS if h not in covered]
SKIP = ("paper_numbers.json", "restatement_index.json", "task_c1_claims_audit.json", "comparative_claims.json", "claims_to_evidence.json")
scan = {}
for f in sorted(os.listdir("results")):
    if not f.endswith(".json") or f in SKIP:
        continue
    try:
        j = J(os.path.join("results", f))
    except Exception:
        continue
    found = set()

    def walk(o, path):
        if isinstance(o, dict):
            for k, v in o.items():
                walk(v, path + [str(k)])
        elif isinstance(o, list) and o and isinstance(o[0], (dict, list)):
            for i, v in enumerate(o[:60]):
                walk(v, path + [f"[{i}]"])
        p = "/".join(path)
        for h in uncovered:
            if path and re.search(r"arm_?B|armB|teacher.forced", p) and re.search(r"(^|/|\|)h?" + str(h) + r"(/|\||$)", p):
                found.add(path[-1])
    walk(j, [])
    if found:
        scan[f] = sorted(found)
# Arm B named by the file rather than by a key: the run records results/step5_armB_seed<s>.json
s5b = {}
for s in (0, 1, 2):
    ev = J(f"results/step5_armB_seed{s}.json")["evaluations"]["2500"]["horizon"]
    if all(str(h) in ev for h in uncovered):
        s5b[s] = {h: ev[str(h)]["e"] for h in [1] + uncovered}
import rollout_eval as E  # noqa: E402
_d, _ep = R.load_data(paths["csv"], verbose=False)
_split = E.make_split(seed=0, strat_path=os.path.join(R.RESULTS, "step0_strat.json"), verbose=False)
s5_idx = E.sample_trajectories(_ep, _split["holdout_episodes"], seed=0)
s5_starts = sorted(int(x) for x in s5_idx[:, 0])
cache_ok, cache_shape = True, None
for x in H2H["input_files"]:
    if "armB_teacher_forced" in x["path"]:
        cache_ok &= os.path.exists(x["path"]) and sha(x["path"]) == x["sha256"]
        if os.path.exists(x["path"]):
            cache_shape = tuple(np.load(x["path"])["err"].shape)
X1["h2h_H"] = at("scripts/head_to_head_accuracy.py", "^HORIZONS = ")
X1["s5_eval"] = at("scripts/step5_train.py", 'idx = E.sample_trajectories(episode_id, split["holdout_episodes"], seed=0)')
X1["ntraj"] = at("src/rollout_eval.py", "^N_TRAJ")
X1["choice"] = at("src/rollout_eval.py", "starts = rng.choice(cand, size=n_traj, replace=len(cand) < n_traj)")
dec = open("docs/presubmission/round4/DECISIONS.md", encoding="utf-8").read()
dsec = dec.split("## F0-armB-2500-h128", 1)[1] if "## F0-armB-2500-h128" in dec else ""
ruling_b = bool(re.search(r"^\*\*Ruling, [0-9-]+: \(B\)\.\*\*", dsec, flags=re.M))
by_ruling = bool(uncovered) and ruling_b and cache_ok and cache_shape is not None and cache_shape[1] >= max(HS)
pf1_artifact_ok = not uncovered or by_ruling
fmt_h = lambda hs: ", ".join(map(str, hs))
scan_txt = "; ".join(f"`{f}` ({', '.join(v[:4])}{' …' if len(v) > 4 else ''})" for f, v in scan.items())
md += ["",
       "**Arm B's 2,500-iteration held-out relative-L1, at every horizon (for X3's assertion).** No single committed artifact holds it.",
       f"- `results/head_to_head_accuracy.json` `rows.armB` (`arm_checkpoint` `{H2H['arm_checkpoint']}`, arena "
       f"\"{H2H['arena']}\", n_independent {H2H['n_independent']}; metric: {H2H['metrics']['l1']}): the three-seed mean "
       f"(`cells`) and each seed's mean (`per_model`), at h = {fmt_h(h2h_h)}. No per-trajectory values.",
       f"- `results/action_sensitivity.json` `per_seed[\"arm_b_2500|seed<s>|held_out_n4|h<h>\"].I0_per_trajectory_err` "
       f"(the unperturbed causal rollout): each trajectory's value per seed, at h = {fmt_h(as_h)} (rule X2 read h ≤ 100 only).",
       f"- The two agree where both exist (h = {fmt_h(shared)}, per-seed means): max |difference| {agree:.1e}. They are the "
       f"statistic X3's Arm A assertion reads: `head_to_head_accuracy.json`'s Arm A row equals `mn_compute_matched.json`'s 2,500 "
       f"block (`part2_centre_at_more_compute.three_seed_mean_l1[\"2500\"].held_out`) to {a_agree:.1e} at h = {', '.join(a_h)}. "
       f"Arm A at every horizon, per trajectory and seed, is in `mn_sweep_eval.json` `configs.M32_N8`.",
       f"- Together the two cover h = {fmt_h(covered)}. **At h = {fmt_h(uncovered) or 'none'}, no committed artifact holds it on "
       f"§5's four non-overlapping trajectories.** A key-path scan of every `results/*.json` for an Arm B block at h = {fmt_h(uncovered)} "
       f"finds only other measures: {scan_txt}.",
       f"- The run records `results/step5_armB_seed<s>.json` (the arm is in the file name, not a key) do hold Arm B's 2,500-iteration "
       f"held-out relative-L1 at h = {fmt_h(uncovered)} (`evaluations[\"2500\"].horizon`, seeds 0-2: "
       f"{', '.join(f'{v[uncovered[0]]:.4f}' for v in s5b.values())}), but on a different arena: {len(s5_idx)} trajectories drawn at random "
       f"from the held-out episodes' valid starts (`scripts/step5_train.py:{X1['s5_eval']}`; `src/rollout_eval.py:{X1['ntraj']}`, `:{X1['choice']}`), starting at "
       f"rows {s5_starts}, overlapping one another, not §5's four. At h = 1 they give {', '.join(f'{v[1]:.4f}' for v in s5b.values())} against "
       f"`head_to_head_accuracy.json`'s {', '.join(f'{h2h_seed[(s, 1)]:.4f}' for s in (0, 1, 2))}, so they cannot serve as X3's reference.",
       f"- The stored rollouts behind `head_to_head_accuracy.json` hold every forecast step on §5's four trajectories: "
       f"`cache/armB_teacher_forced_seed<s>__out-of-sample_held-out_pair__u400.npz` (`err`, {cache_shape}), git-ignored, each SHA-256 equal to the one "
       f"`head_to_head_accuracy.json` `input_files` records: {'yes' if cache_ok else 'NO'}. That script reports h = {fmt_h(h2h_h)} only "
       f"(`scripts/head_to_head_accuracy.py:{X1['h2h_H']}`).",
       f"- So X3's assertion as Annex 2 words it (\"Arm B (PF1's artifact) at every horizon, to 1e-6\") has no committed "
       f"reference at h = {fmt_h(uncovered)}. The question is `DECISIONS.md#F0-armB-2500-h128`.",
       (f"- **Ruling (B)** (`DECISIONS.md#F0-armB-2500-h128`): F1 builds the six-horizon Arm B reference from those stored rollouts before "
        f"X3's pre-registration, and X3 asserts against it at every horizon. The rollouts exist, match their recorded SHA-256s and hold "
        f"{cache_shape[1] if cache_shape else 0} forecast steps (h = {max(HS)} needs {max(HS)}), so the reference X3 needs can be built: "
        f"{'yes' if by_ruling else 'NO'}.\n") if ruling_b else
       "- No ruling yet.\n"]
p1_weights = not any(missing.values()) and ck_ok and not sha_bad and all(t[2] for t in twin)
p1 = p1_weights and pf1_artifact_ok
verdicts["PF1"] = p1
md.append(f"**PF1: {'PASS' if p1 else 'FAIL'}** — weights: {'all present, checksums verified' if p1_weights else 'INCOMPLETE'}; "
          f"Arm B reference: {'found' if not uncovered else ('to be built by F1 from the stored rollouts, under ruling (B)' if by_ruling else 'missing at h = ' + fmt_h(uncovered))}.\n")

# ================================================================ PF2 the split
import rollout_eval as E  # noqa: E402
import rwm_metrics as MET  # noqa: E402
data, ep = R.load_data(paths["csv"], verbose=False)
split = E.make_split(seed=0, strat_path=os.path.join(R.RESULTS, "step0_strat.json"), verbose=False)
s5 = "scripts/step5_train.py"
args5 = [l.split("add_argument(")[1].split(",")[0].strip('"') for l in open(s5) if "ap.add_argument(" in l]
held_arg = [a for a in args5 if re.search(r"hold|held|fold|split|episode", a)]
committed = J("results/step5_armA_seed0.json")["hyperparameters"]
committed_b = J("results/step5_armB_seed0.json")["hyperparameters"]
L = {e: int((ep == e).sum()) for e in range(R.N_EPISODES)}
strat = J(os.path.join(R.RESULTS, "step0_strat.json"))
speed = {e: strat[str(e)]["mean_speed"] for e in range(R.N_EPISODES)}
order = sorted(range(R.N_EPISODES), key=lambda e: -speed[e])
fast = set(order[:R.N_EPISODES // 2])
FOLDS = [[1, 8], [0, 2], [3, 4], [5, 6], [7, 9]]
MN = importlib.import_module("mn_sweep_eval")
RT = importlib.import_module("rwm_train")
win = RT.WINDOW
rows2, n_total = [], 0
for f in FOLDS:
    st = MET.non_overlapping_starts(ep, f, 400)
    tr = [e for e in range(R.N_EPISODES) if e not in f]
    nw = len([s for s in R.valid_window_starts(ep, win) if ep[s] in tr])
    n_total += MET.n_independent(st, 400)
    rows2.append((f, len(st), MET.n_independent(st, 400), st, nw, ["fast" if e in fast else "slow" for e in f]))
win_ok = rows2[0][4] == committed["n_train_windows"] == committed_b["n_train_windows"]
starts_ok = rows2[0][3] == list(MN.HELD_OUT_STARTS)
every_once = sorted(e for f in FOLDS for e in f) == list(range(R.N_EPISODES))
X2 = {"make_split": at("src/rollout_eval.py", "^def make_split"),
      "strat": at("src/rollout_eval.py", "holdout = np.sort([rng.choice(fast)"),
      "s5_split": at(s5, "split = E.make_split(seed=0"),
      "a1_split": at("scripts/a1_ab_by_horizon.py", "split = E.make_split(seed=0"),
      "held": at("scripts/mn_sweep_eval.py", "^HELD_OUT_STARTS"),
      "held_assert": at("scripts/mn_sweep_eval.py", 'assert arenas["held_out"]["starts"] == HELD_OUT_STARTS'),
      "arg0": at(s5, 'ap.add_argument("--arm"'), "arg1": at(s5, 'ap.add_argument("--out-dir"'),
      "wds": at("src/rwm_train.py", "^class WindowDataset"), "vws": at("src/rwm_data.py", "^def valid_window_starts"),
      "WINDOW": at("src/rwm_train.py", "^WINDOW = "),
      "nos": at("src/rwm_metrics.py", "^def non_overlapping_starts"), "nind": at("src/rwm_metrics.py", "^def n_independent")}
same_half = [f for f, n, ni, st, nw, h in rows2[1:] if len(set(h)) == 1]
md += ["## PF2 — the train/held-out split\n",
       f"- **Where {{1, 8}} is set.** `src/rollout_eval.py:{X2['make_split']}` `make_split(seed=0, n_holdout=2, strat_path=…)` "
       f"draws one fast and one slow episode by mean commanded speed (`:{X2['strat']}`), from `results/step0_strat.json`; with "
       f"seed 0 it returns train {split['train_episodes']}, held-out {split['holdout_episodes']}. The training driver calls it with "
       f"a literal seed (`{s5}:{X2['s5_split']}`), as the evaluators do (e.g. `scripts/a1_ab_by_horizon.py:{X2['a1_split']}`), and "
       f"`scripts/mn_sweep_eval.py` defines §5's four trajectory starts {list(MN.HELD_OUT_STARTS)} (`:{X2['held']}`) and asserts "
       f"them (`:{X2['held_assert']}`).",
       f"- **Does the driver take the held-out set as an argument?** {'Yes: ' + ', '.join(held_arg) if held_arg else 'No.'} "
       f"Its arguments are {', '.join('`' + a + '`' for a in args5)} (`{s5}:{X2['arg0']}-{X2['arg1']}`). F1 item 1 adds one.",
       f"- **How training windows are built.** `src/rwm_train.py:{X2['wds']}` `WindowDataset` keeps every start from "
       f"`src/rwm_data.py:{X2['vws']}` `valid_window_starts(episode_id, window)` whose window lies inside one training episode "
       f"(rows s … s + window − 1 in one episode, none in the discarded stub), with window = M + N = {win} (`src/rwm_train.py:{X2['WINDOW']}`). "
       f"An episode of L rows therefore gives L − {win - 1} windows. Episode lengths: "
       f"{', '.join(f'{e}: {L[e]:,}' for e in range(R.N_EPISODES))} rows, plus {int((ep < 0).sum())} stub row.",
       f"- **The committed window count for {{1, 8}}.** `results/step5_armA_seed0.json` and `results/step5_armB_seed0.json` "
       f"`hyperparameters.n_train_windows` = {committed['n_train_windows']:,} and {committed_b['n_train_windows']:,}; recounted here, "
       f"{rows2[0][4]:,} ({'equal' if win_ok else 'DIFFERENT'}). Their `train_episodes` are {committed['train_episodes']} and "
       f"`holdout_episodes` {committed['holdout_episodes']}.",
       "",
       "| Fold (held out) | Non-overlapping 400-step trajectories | n_independent | Start rows | Training windows | Speed halves |",
       "|---|---:|---:|---|---:|---|"]
md += [f"| {{{', '.join(map(str, f))}}} | {n} | {ni} | {st} | {nw:,} | {', '.join(h)} |" for f, n, ni, st, nw, h in rows2]
md += ["",
       f"Counted by `src/rwm_metrics.py:{X2['nos']}` `non_overlapping_starts` and `:{X2['nind']}` `n_independent`, the functions "
       f"§5's arena uses. Pooled over the five folds, n = {n_total}; every episode is held out exactly once: "
       f"{'yes' if every_once else 'NO'}. Fold {{1, 8}}'s starts equal `HELD_OUT_STARTS`: {'yes' if starts_ok else 'NO'}.",
       f"- Note for F1: `make_split` stratifies {{1, 8}} by speed (one fast, one slow); the four new folds pair episodes in index "
       f"order, so {' and '.join('{' + ', '.join(map(str, f)) + '}' for f in same_half) or 'none'} hold two episodes from the same "
       f"speed half. Annex 2 fixes the folds; this is recorded, not a deviation.\n"]
p2 = win_ok and starts_ok and every_once and all(ni == 4 for _, _, ni, _, _, _ in rows2)
verdicts["PF2"] = p2
md.append(f"**PF2: {'PASS' if p2 else 'FAIL'}.**\n")

# ================================================================ PF3 size-matched baselines
import baselines as BL  # noqa: E402
import torch  # noqa: E402
cfg = R.load_reference_config(paths["lite"])
BS = "docs/presubmission/BASELINE_SPECS.md"
spec_rows = {}
for i, l in enumerate(open(BS, encoding="utf-8")):
    m = re.match(r"\| (3[3-8]) \| ([^|]+)\| ([^|]+)\| ([^|]+)\| ([^|]+)\|", l)
    if m:
        spec_rows[int(m.group(1))] = (i + 1, m.group(2).strip(), m.group(3).strip(), m.group(4).strip(), m.group(5).strip())
assert sorted(spec_rows) == list(range(33, 39)), sorted(spec_rows)
counts = {}
for arch in ("mlp", "transformer", "rssm"):
    torch.manual_seed(0)
    counts[arch] = BL.n_params(BL.build(arch, "matched", cfg))
BV = J("results/baseline_verification.json")
bv = BV["baselines"]
row_arch = {33: "mlp", 34: "transformer", 35: "rssm", 36: "rssm", 37: "rssm", 38: "rssm"}
X3_ = {"build": at("src/baselines/__init__.py", "^def build"),
       "regimes": at("scripts/baseline_verification.py", 'regimes = ("tf", "ar") if spec == "s7"')}
md += ["## PF3 — size-matched baselines\n",
       f"`{BS}` rows 33-38, read from the file. Each row's model is built now through `src/baselines/__init__.py:{X3_['build']}` "
       f"`build(arch, \"matched\", cfg)` and counted with `n_params` (every parameter; the baselines have no auxiliary heads). "
       f"RWM's ensemble-1 state pathway: {BL.RWM_STATE_PATHWAY:,} (`results/baseline_verification.json` "
       f"`rwm_state_pathway_params` = {BV['rwm_state_pathway_params']:,}).\n",
       "| Row | Item | Choice | Status | Citation or reason | Model | Parameters, built now | Ratio to RWM | Ladder's count |",
       "|---:|---|---|---|---|---|---:|---:|---:|"]
unverified = []
for r in range(33, 39):
    lno, item, choice, status, cite = spec_rows[r]
    a = row_arch[r]
    lad = bv.get(f"{a}_matched", {}).get("n_params")
    if "UNVERIFIED" in status.upper():
        unverified.append(r)
    md.append(f"| {r} (`BASELINE_SPECS.md:{lno}`) | {item} | {choice} | {status} | {cite} | {a} | {counts[a]:,} | "
              f"{counts[a] / BL.RWM_STATE_PATHWAY:.3f} | {f'{lad:,}' if lad else '—'} |")
within = {a: abs(counts[a] / BL.RWM_STATE_PATHWAY - 1) <= 0.05 for a in counts}
lad_eq = all(bv.get(f"{a}_matched", {}).get("n_params") == counts[a] for a in counts)
regimes = {a: sorted(bv.get(f"{a}_matched", {}).get("memorise", {}).keys()) for a in counts}
md += ["",
       f"- UNVERIFIED rows among 33-38: {unverified or 'none'}. Every count within ±5% of {BL.RWM_STATE_PATHWAY:,}: "
       f"{'yes' if all(within.values()) else 'NO: ' + str(within)}; equal to the verification ladder's: {'yes' if lad_eq else 'NO'}.",
       f"- Note for F1 item 2: the ladder ran its memorisation and determinism checks for the matched variants in the "
       f"regimes {regimes['mlp']} (MLP) and {regimes['transformer']} (transformer) only "
       f"(`scripts/baseline_verification.py:{X3_['regimes']}`); X4 trains them autoregressively, a regime the ladder verified "
       f"for the Table S7 sizes alone.\n"]
p3 = not unverified and all(within.values()) and lad_eq
verdicts["PF3"] = p3
md.append(f"**PF3: {'PASS' if p3 else 'FAIL'}.**\n")

# ================================================================ PF4 reward computability (records only)
ENV = f"{LITE}/scripts/envs/anymal_d_flat.py"
BASE = f"{LITE}/scripts/envs/base.py"
ECFG = f"{LITE}/scripts/configs/anymal_d_flat_cfg.py"
BCFG = f"{LITE}/scripts/configs/base_cfg.py"
wtxt, btxt = open(ECFG, encoding="utf-8").read(), open(BCFG, encoding="utf-8").read()
pen_w = re.search(r"uncertainty_penalty_weight: float = (-?[0-9.]+)", wtxt).group(1)
pen_w_base = re.search(r"uncertainty_penalty_weight: float = (-?[0-9.]+)", btxt).group(1)
dt_v = re.search(r"step_dt: float = ([0-9.]+)", btxt).group(1)
X4_ = {"csv": at("src/rwm_data.py", '"csv"'), "hdr": at("src/rwm_data.py", "header=None"),
       "cm0": at("src/rwm_data.py", "# column map"), "cm1": at("src/rwm_data.py", "^TERMINATION = "),
       "init_cmd": at(ENV, "def _init_imagination_command"), "reset_cmd": at(ENV, "def _reset_imagination_command"),
       "step0": at("scripts/step0_velocity_regimes.py", "commanded velocity is not recorded"),
       "dt_cfg": at(BCFG, "step_dt: float ="), "dt_store": at(BASE, "self._step_dt = step_dt"), "DT": at("src/rwm_data.py", "^DT = "),
       "pen": at(BASE, "rewards += self.uncertainty_penalty_weight * self.epistemic_uncertainty * self._step_dt"),
       "pen_w": at(ECFG, "uncertainty_penalty_weight: float ="), "pen_w_base": at(BCFG, "uncertainty_penalty_weight: float ="),
       "epis": at(BASE, "self.epistemic_uncertainty, extensions, contacts"),
       "other": at(BASE, "rewards += self.reward_term_weights[term] * term_value * self._step_dt"),
       "terms": at(ENV, "def _compute_imagination_reward_terms"),
       "obs": at(ENV, "def get_imagination_observation"), "first": at(ENV, "first_contact = "),
       "lat": at(ENV, "self.last_air_time = torch.where")}
TERMS = [("track_lin_vel_xy_exp", "track_lin_vel_xy_exp = ", "commanded velocity `base_velocity[:, :2]` against the forecast `base_lin_vel[:, :2]` (error at :{e1}); exp(−error/0.25)", "lin_vel_error = "),
         ("track_ang_vel_z_exp", "track_ang_vel_z_exp = ", "commanded yaw rate `base_velocity[:, 2]` against the forecast `base_ang_vel[:, 2]` (error at :{e1}); exp(−error/0.25)", "ang_vel_error = "),
         ("lin_vel_z_l2", "lin_vel_z_l2 = ", "forecast `base_lin_vel[:, 2]`, squared", None),
         ("ang_vel_xy_l2", "ang_vel_xy_l2 = ", "forecast `base_ang_vel[:, :2]`, sum of squares", None),
         ("dof_torques_l2", "dof_torques_l2 = ", "forecast `joint_torque`, sum of squares", None),
         ("dof_acc_l2", "dof_acc_l2 = ", "`joint_acc = (joint_vel − last_obs[\"policy\"][:, 12:24]) / dt` (:{e1}), sum of squares", "joint_acc = "),
         ("action_rate_l2", "action_rate_l2 = ", "`obs_last_action` (the previous action) against the current action, sum of squares", None),
         ("feet_air_time", "feet_air_time = torch.sum", "forecast foot contacts (the contact head) driving env-held air/contact timers advanced by dt; gated by ‖command xy‖ > 0.1", None),
         ("undesired_contacts", "undesired_contacts = ", "forecast thigh contacts (the contact head), summed", None),
         ("stand_still", "stand_still = ", "Σ|forecast `joint_pos`|, gated by ‖command‖ < 0.05", None),
         ("flat_orientation_l2", "flat_orientation_l2 = ", "forecast `projected_gravity[:, :2]`, sum of squares", None),
         ("dof_pos_limits", "dof_pos_limits = ", "none: identically zero", None)]
COLS = [("base linear velocity", R.LIN_VEL), ("base angular velocity", R.ANG_VEL), ("projected gravity", R.GRAVITY),
        ("joint positions", R.JOINT_POS), ("joint velocities", R.JOINT_VEL), ("joint torques", R.JOINT_TAU),
        ("actions", R.ACTIONS), ("thigh contact labels", R.CONTACT_THIGH), ("foot contact labels", R.CONTACT_FOOT),
        ("termination", [R.TERMINATION])]
cont = np.asarray(R.CONTACTS)
cvals = sorted(set(np.unique(data[:, cont]).tolist()))
th = data[:, R.CONTACT_THIGH]
th_rows = [int(r) for r in np.flatnonzero(th.max(1) > 0)]
# the policy observation's layout, from get_imagination_observation's own slices and torch.cat order
env_lines = open(ENV, encoding="utf-8").read().split("\n")
o0 = at(ENV, "def get_imagination_observation")
widths = {}
for l in env_lines[o0:o0 + 12]:
    m = re.search(r"(obs_\w+) = state_history_denormalized\[:, (\d+):(\d+)\]", l)
    if m:
        widths[m.group(1)] = int(m.group(3)) - int(m.group(2))
widths["self.base_velocity"] = 3 if "self.base_velocity = torch.zeros(self.num_envs, 3" in open(ENV).read() else None
widths["self.obs_last_action"] = R.ACTION_DIM
cat_ln = at(ENV, "obs = torch.cat([obs_base_lin_vel")
cat = re.search(r"torch\.cat\(\[([^\]]+)\]", env_lines[cat_ln - 1]).group(1).replace(" ", "").split(",")
obs_cols, c0 = {}, 0
for nm in cat:
    obs_cols[nm] = (c0, c0 + widths[nm])
    c0 += widths[nm]
md += ["## PF4 — reward computability (records only)\n",
       f"**The data.** `src/rwm_data.py:{X4_['csv']}` names the released CSV, `lite/assets/data/{os.path.basename(paths['csv'])}`: "
       f"{data.shape[0]:,} rows × {data.shape[1]} columns with no header row (read with `header=None`, `src/rwm_data.py:{X4_['hdr']}`), "
       f"so the columns have no names in the file. The repository's column map (`src/rwm_data.py:{X4_['cm0']}-{X4_['cm1']}`):"]
md += [f"  - {lab}: column{'s' if len(v) > 1 else ''} {min(v)}{'-' + str(max(v)) if len(v) > 1 else ''}" for lab, v in COLS]
md += [f"- **Velocity commands: not present.** No column holds a command; the imagination environment samples its own "
       f"(`lite/scripts/envs/anymal_d_flat.py:{X4_['init_cmd']}` and `:{X4_['reset_cmd']}`: uniform in [−1, 1] per axis, 2% standing). "
       f"The repository infers the commanded regimes from achieved base velocity instead "
       f"(`scripts/step0_velocity_regimes.py:{X4_['step0']}`, \"The commanded velocity is not recorded in the 66 columns\").",
       f"- **Contact labels: present**, {len(cont)} binary columns (values {cvals}). Of the four thigh labels' {th.size:,} cells, "
       f"{int((th > 0).sum())} {'is' if int((th > 0).sum()) == 1 else 'are'} set to 1 (row{'s' if len(th_rows) != 1 else ''} "
       f"{', '.join(f'{r:,}' for r in th_rows)}, episode {', '.join(str(int(ep[r])) for r in th_rows)}); the four foot labels' means are "
       f"{', '.join(f'{m:.2f}' for m in data[:, R.CONTACT_FOOT].mean(0))}. No contact forces are recorded.",
       f"- **dt** = {dt_v} s, a literal (`lite/scripts/configs/base_cfg.py:{X4_['dt_cfg']}`; `anymal_d_flat_cfg.py` does not override it), "
       f"stored as `self._step_dt` (`lite/scripts/envs/base.py:{X4_['dt_store']}`). The repository's own copy is "
       f"`src/rwm_data.py:{X4_['DT']}` (`DT = {R.DT}`).",
       f"- **The penalty** is added at `lite/scripts/envs/base.py:{X4_['pen']}` as `uncertainty_penalty_weight * epistemic_uncertainty * dt`, "
       f"with weight {pen_w} (`lite/scripts/configs/anymal_d_flat_cfg.py:{X4_['pen_w']}`, overriding `base_cfg.py:{X4_['pen_w_base']}`'s {pen_w_base}); "
       f"`epistemic_uncertainty` comes from the model's forward pass (`base.py:{X4_['epis']}`). Every other term is added as "
       f"`reward_term_weights[term] * term_value * dt` (`base.py:{X4_['other']}`).",
       "",
       f"Every reward term the imagination environment computes (`lite/scripts/envs/anymal_d_flat.py:{X4_['terms']}`), with its weight. "
       "\"Command\" is the environment's sampled command, which the data do not hold; \"forecast\" is the model's output.\n",
       "| Term | file:line | Inputs | Weight (`anymal_d_flat_cfg.py`) |", "|---|---|---|---|"]
for t, needle, inp, extra in TERMS:
    l0 = at(ENV, needle)
    e1 = at(ENV, extra) if extra else None
    w = re.search(r'"' + t + r'": (-?[0-9.e-]+)', wtxt).group(1)
    wl = at(ECFG, '"' + t + '":')
    md.append(f"| `{t}` | `anymal_d_flat.py:{l0}` | {inp.format(e1=e1)} | {w} (`:{wl}`) |")
md += [f"| `uncertainty` (the penalty) | `base.py:{X4_['pen']}` | the ensemble's epistemic uncertainty | {pen_w} (`:{X4_['pen_w']}`) |",
       "",
       f"Upstream details recorded for F2, not judged here. The policy observation (`anymal_d_flat.py:{cat_ln}`, built in "
       f"`get_imagination_observation` at `:{X4_['obs']}`) is {c0} columns: "
       + ", ".join(f"`{nm.replace('self.', '')}` {a}:{b}" for nm, (a, b) in obs_cols.items())
       + f". It includes the command, which the data do not hold. `dof_acc_l2`'s `last_obs[\"policy\"][:, 12:24]` is therefore "
       f"`{next(nm for nm, (a, b) in obs_cols.items() if (a, b) == (12, 24)).replace('self.', '')}`, subtracted from the joint velocity. "
       f"`feet_air_time` reads the contact timers before this step's update (`:{X4_['first']}` before `:{X4_['lat']}`).\n",
       "**PF4: recorded** (records only; no verdict).\n"]
verdicts["PF4"] = None

# ================================================================ PF5 the action-convention evidence
LED = "FINDINGS_LEDGER.md"
d13 = at(LED, "### D-13 ")
d13_text = "".join(open(LED, encoding="utf-8").readlines()[d13 - 1:d13 + 40])
d13_src = re.search(r"`ActionManager\.reset\(\)`, `([^`]+)`,\s*commit `([0-9a-f]{40})`", d13_text)
d13_tests = len(re.findall(r"^\| 1[bcd]? \|", d13_text, flags=re.M))
cands = ["PAPER.template.md", "README.template.md", "MODEL_CARD.md", "scripts/build_model_card.py"] + \
        sorted(os.path.join("docs", f) for f in os.listdir("docs") if f.endswith(".template.md"))
hits5 = {}
for f in cands:
    if os.path.exists(f):
        v = [i + 1 for i, l in enumerate(open(f, encoding="utf-8")) if re.search(r"ActionManager|action_manager", l)]
        if v:
            hits5[f] = v
reset_arg = at("PAPER.template.md", "Row *t* holds the action that *produced* state *t*")
src_txt = (f"`ActionManager.reset()` at `{d13_src.group(1)}`, Isaac Lab commit `{d13_src.group(2)[:8]}`, which zeroes "
           f"`_prev_action` and `_action`") if d13_src else "NO ActionManager citation"
md += ["## PF5 — the action-convention evidence\n",
       f"- Ledger D-13 (`{LED}:{d13}`) cites {d13_tests} tests (rows 1, 1b, 1c and 1d of its table) and {src_txt}.",
       f"- Does the paper cite it? Searching `PAPER.template.md`, `README.template.md`, `MODEL_CARD.md`, `scripts/build_model_card.py` "
       f"and every `docs/*.template.md` for `ActionManager` or `action_manager`: **{'no hits, so it is uncited' if not hits5 else 'cited: ' + str(hits5)}**. "
       f"§7.2's reset-row argument is at `PAPER.template.md:{reset_arg}` (\"Row *t* holds the action that *produced* state *t*\"); "
       f"F4 item 1 adds the citation.\n"]
p5 = bool(d13_src)
verdicts["PF5"] = p5
md.append(f"**PF5: {'PASS' if p5 else 'FAIL'}** (D-13 holds the source line; the paper does not yet cite it).\n")

# ================================================================ PF6 functions to import
A1 = importlib.import_module("a1_ab_by_horizon")
RB = importlib.import_module("review_bootstrap_unit")
a1j = J("results/a1_ab_by_horizon.json")
dev, dev_inline = 0.0, 0.0
for h, b in a1j["by_horizon"].items():
    g = np.array(b["gap_per_trajectory"])
    rng = np.random.default_rng(A1.BOOT_SEED)
    draws = rng.integers(0, len(g), size=(A1.N_BOOT, len(g)))
    lo, hi = np.percentile(g[draws].mean(1), [2.5, 97.5])
    _, lo2, hi2 = RB.boot_cluster(np.array(b["A_per_trajectory"])[None], np.array(b["B_per_trajectory"])[None],
                                  n=A1.N_BOOT, seed=A1.BOOT_SEED)
    dev_inline = max(dev_inline, abs(lo - b["gap_ci"][0]), abs(hi - b["gap_ci"][1]))
    dev = max(dev, abs(lo2 - b["gap_ci"][0]), abs(hi2 - b["gap_ci"][1]))
E7 = "scripts/e7_free_baselines.py"
vm, vb, A1S = "scripts/verdict_mn_sweep.py", "scripts/verdict_baselines.py", "scripts/a1_ab_by_horizon.py"
F6 = [("M-64's short-unit index builder", "scripts/m64_short_units.py", "^def build_index", "function"),
      ("M-64's short-unit rollout (causal pairing)", "scripts/m64_short_units.py", "^def unit_rollout", "function"),
      ("M-64's two-level cluster bootstrap", "scripts/m64_short_units.py", "^def boot_ci", "function"),
      ("the free-baselines correlation", E7, "^def _corr", "function"),
      ("the free-baselines partial correlation", E7, "^def _partial", "function"),
      ("the free-baselines margin r(disagreement, |error|) − r(baseline, |error|), and its interval", E7, '"margin": r_dis - r_b', "inline in `main()`"),
      ("§6.7's per-horizon fit (`fit_scalar`)", "scripts/task_d3_perhorizon.py", "^def fit_scalar", "function"),
      ("§6.7's per-horizon score (`cover`)", "scripts/task_d3_perhorizon.py", "^def cover", "function"),
      ("§6.7's fit, in the cross-model successor", "scripts/task_d3_cross_model.py", "^def fit_scalar", "function"),
      ("§6.7's score, in the cross-model successor", "scripts/task_d3_cross_model.py", "^def cover", "function"),
      ("M-23's own verdict bootstrap (seed 1 only)", "scripts/task5_analyse.py", "^def boot(", "function"),
      ("M-23's three-seed bootstrap (§5's by-horizon table)", A1S, "boots = gap_traj[draws].mean(1)", "inline in `main()`"),
      ("the three-seed bootstrap, as a function", "scripts/review_bootstrap_unit.py", "^def boot_cluster", "function"),
      ("`verdict_mn_sweep`'s verdict", vm, "^def main_verdict", "function"),
      ("`verdict_baselines`' overall label", vb, "^def overall", "function"),
      ("`verdict_baselines`' verdict", vb, "^def main_verdict", "function"),
      ("`action_sensitivity`'s intervention hook", "scripts/action_sensitivity.py", "^class Hook", "class"),
      ("`action_sensitivity`'s interval", "scripts/action_sensitivity.py", "^def e_with_ci", "function"),
      ("`action_sensitivity`'s exact / Monte Carlo draws", "scripts/action_sensitivity.py", "^def draws_for", "function")]
md += ["## PF6 — functions to import\n", "| Statistic | file:line | Form |", "|---|---|---|"]
missing6 = []
for what, f, needle, form in F6:
    try:
        md.append(f"| {what} | `{f}:{at(f, needle)}` | {form} |")
    except AssertionError:
        missing6.append(what)
        md.append(f"| {what} | NOT FOUND | — |")
vm_fns = ", ".join(f"`{n}` :{at(vm, '^def ' + n + '(')}" for n in ("seed_mean", "differences", "family", "holm", "branch", "main_verdict"))
vb_fns = ", ".join(f"`{n}` :{at(vb, '^def ' + n + '(')}" for n in ("overall", "per_baseline", "family", "seed_mean", "differences", "one_rule", "main_verdict"))
X6_ = {"margin": at(E7, '"margin": r_dis - r_b'), "boot": at(E7, "    def boot("), "draw": at(A1S, "draws = rng.integers(0, len(starts)"),
       "stat": at(A1S, "boots = gap_traj[draws].mean(1)"), "bc": at("scripts/review_bootstrap_unit.py", "^def boot_cluster"),
       "df": at("scripts/action_sensitivity.py", "^def draws_for")}
md += ["",
       f"Reading functions in full: `verdict_mn_sweep.py` {vm_fns}; `verdict_baselines.py` {vb_fns}.",
       f"- **Two of the named statistics are not importable functions.** The free-baselines margin is computed inline "
       f"(`{E7}:{X6_['margin']}`) from the importable `_corr`, with its interval from a closure inside `main()` (`:{X6_['boot']}`). "
       f"M-23's three-seed bootstrap is inline in `{A1S}`'s `main()` (draws `:{X6_['draw']}`, statistic `:{X6_['stat']}`; "
       f"{A1.N_BOOT:,} Monte Carlo draws, seed {A1.BOOT_SEED}, seeds pooled inside each draw).",
       f"- **An importable equivalent of the three-seed bootstrap reproduces it.** `scripts/review_bootstrap_unit.py:{X6_['bc']}` "
       f"`boot_cluster(Am, Bm, n, seed)` resamples whole trajectories, carrying every seed. With n = {A1.N_BOOT:,} and seed "
       f"{A1.BOOT_SEED}, fed `results/a1_ab_by_horizon.json`'s per-trajectory values, it reproduces that file's `gap_ci` at all "
       f"{len(a1j['by_horizon'])} horizons to {dev:.1e} (the inline formula, re-run on the same values: {dev_inline:.1e}; both are the "
       f"float32 rounding of the stored values).",
       f"- **It is Monte Carlo at n = 4.** Annex 2 defines an interval as \"exact over all ordered resamples at n = 4\"; the three-seed "
       f"bootstrap draws {A1.N_BOOT:,} Monte Carlo resamples there too. X3's pooled interval (n = 20) is unaffected. Its per-fold "
       f"\"exact interval\" (n = 4) needs exhaustive draws, which `scripts/action_sensitivity.py:{X6_['df']}` `draws_for(n)` provides "
       f"(all 4⁴ ordered resamples at n = 4) and `verdict_baselines.family(…, exact=True)` uses. Recorded for F1.\n"]
p6 = not missing6
verdicts["PF6"] = p6
md.append(f"**PF6: {'PASS' if p6 else 'FAIL'}** (every named statistic located{'; missing: ' + ', '.join(missing6) if missing6 else ''}; "
          "importability recorded for F1 and F2).\n")

# ================================================================ PF7 the difficulty measure
A2S = "scripts/a2_trajectory_level_control.py"
X7_ = {"a": at(A2S, "# D-12's per-episode difficulty, averaged over the seeds"), "b": at(A2S, "diff_by_ep[e] = float(np.mean(vals))"),
       "src": at(A2S, '"difficulty_source":'), "d37": at("FINDINGS_LEDGER.md", "### D-37 ")}
pe = J("results/step4_0a_results.json")["per_episode_e"]
PN = "scripts/paper_numbers.py"
a2j = J("results/a2_trajectory_level_control.json")["h1_diagnostic"]
pn_lines = open(PN, encoding="utf-8").read().split("\n")
keys7 = []
for i, l in enumerate(pn_lines):
    m = re.search(r'put\("([A-Za-z0-9_]+)"', l)
    if m:
        block = " ".join(pn_lines[i:i + 3]).split("put(")[1]
        if re.search(r'_h1\["(episode_difficulty_range|partial_on_both)"\]|_h1\["confounders"\]\["episode_difficulty_D12"\]', block):
            keys7.append((m.group(1), i + 1))
tpl = open("PAPER.template.md", encoding="utf-8").read().split("\n")
heads = [(i, l) for i, l in enumerate(tpl) if re.match(r"^#{2,3} ", l)]


def section_of(lineno):
    h = [l for i, l in heads if i < lineno]
    return h[-1].strip() if h else "(front matter)"


uses = {k: [i + 1 for i, l in enumerate(tpl) if "{{" + k + "}}" in l] for k, _ in keys7}
other_users = sorted(f for f in os.listdir("scripts") if f.endswith(".py") and f not in ("paper_numbers.py", os.path.basename(A2S))
                     and "a2_trajectory_level_control.json" in open(os.path.join("scripts", f), encoding="utf-8").read())
causal = pe["1"]
md += ["## PF7 — the difficulty measure\n",
       f"- `{A2S}:{X7_['a']}-{X7_['b']}` builds each episode's difficulty as the mean of `per_episode_e[s][e]` over every key `s` "
       f"(the comment calls them seeds), and `:{X7_['src']}` labels it \"{a2j['difficulty_source']}\".",
       f"- `results/step4_0a_results.json` `per_episode_e` has the keys {sorted(pe)}, each holding episodes {sorted(pe[sorted(pe)[0]], key=int)}. "
       f"The keys are action offsets, 0 (stale) and 1 (causal), as ledger D-37 records (`FINDINGS_LEDGER.md:{X7_['d37']}`).",
       f"- The range the paper prints now (the averaged measure): {a2j['episode_difficulty_range'][0]:.3f} to "
       f"{a2j['episode_difficulty_range'][1]:.3f}. At the causal offset alone, from the same file: {min(causal.values()):.3f} to {max(causal.values()):.3f}.",
       "- Paper keys bound from the averaged measure (`scripts/paper_numbers.py` lines that read `h1_diagnostic`'s difficulty fields), "
       "and where the template uses them:\n",
       "| Key | `paper_numbers.py` line | `PAPER.template.md` line | Section |", "|---|---:|---|---|"]
for k, l0 in keys7:
    md.append(f"| `{k}` | {l0} | {', '.join(map(str, uses[k])) or 'unused'} | {'; '.join(sorted(set(section_of(u) for u in uses[k])))} |")
md += ["",
       "`{{a2_h1_diff_r}}` is Appendix N's \"+0.040 with per-episode difficulty\", and `{{a2_h1_partial_both}}` the h = 1 partial "
       "on both confounders. The partial on difficulty alone (`confounders.episode_difficulty_D12.partial_r`) is bound to no key. "
       f"Other scripts that read the artifact, for N6 to check: {', '.join('`scripts/' + f + '`' for f in other_users) or 'none'}.\n"]
p7 = sorted(pe) == ["0", "1"] and bool(keys7)
verdicts["PF7"] = p7
md.append(f"**PF7: {'PASS' if p7 else 'FAIL'}.**\n")

# ================================================================ PF8 action offsets in our evaluators
MSE, BLE = "scripts/mn_sweep_eval.py", "scripts/baselines_eval.py"
_od = []
for root in ("scripts", "src"):
    for r_, _, fs in os.walk(root):
        for f in sorted(fs):
            if f.endswith(".py"):
                fp = os.path.join(r_, f)
                for i, l in enumerate(open(fp, encoding="utf-8")):
                    m = re.match(r"\s*def (\w+)\(([^)]*)", l)
                    if m and re.search(r"\b(action_)?offset\b", m.group(2)):
                        _od.append(f"`{fp}:{i + 1}` `{m.group(1)}`")
offset_defs = ", ".join(sorted(_od))
X8_ = {"ro": at("src/rwm_model.py", "def rollout(self, state, action, start_step, action_offset=1)"),
       "ain": next(i for i in [n + 1 for n, l in enumerate(open("src/rwm_model.py").read().split("\n"))
                               if "a_in = action[:, i - 1 + action_offset:i + action_offset]" in l]
                   if i > at("src/rwm_model.py", "def rollout(self, state, action, start_step, action_offset=1)")),
       "ref": at("src/score_reference.py", "def rollout(self, state, action, start_step=32, action_offset=0"),
       "adc": at("scripts/alignment_defect_ci.py", "^def rollout(model, data, cfg, idx, offset)"),
       "score": at(MSE, "^def score("), "score_off": at(MSE, "action_offset=1)"),
       "eval": at(BLE, "^def evaluate("), "c_ass": at("src/baselines/common.py", "assert action_offset == 1"),
       "r_ass": at("src/baselines/rssm.py", "assert action_offset == 1"), "arf": at("src/baselines/common.py", "^def action_rows_for"),
       "r_tr": at("src/baselines/rssm.py", "h, hstate, prior = self._transition(hstate, z, action[:, t])"),
       "a1": at(A1S, "^def rel_l1_per_traj"), "a1_off": at(A1S, "action_offset=1)"),
       "d1": at("scripts/task_d1_threeseed.py", "^def per_traj"), "d1_off": at("scripts/task_d1_threeseed.py", "action_offset=1)"),
       "t5": at("scripts/task5_analyse.py", "^def traj("), "t5_off": at("scripts/task5_analyse.py", "action_offset=1)")}
md += ["## PF8 — action offsets in our evaluators\n",
       f"Reference: `src/rwm_model.py:{X8_['ro']}` `RWMEnsemble.rollout(…, action_offset=1)` reads `action[:, i − 1 + offset : i + offset]` "
       f"after the first step (`:{X8_['ain']}`). Offset 1 pairs the prediction of state *i* with action *i* (causal, training's pairing); "
       f"offset 0 pairs it with action *i* − 1 (the released evaluation's). The released checkpoint's wrapper defaults to 0 "
       f"(`src/score_reference.py:{X8_['ref']}`). Functions that take an offset as an argument, by a search of `scripts/` and `src/` "
       f"for a `def` whose parameters name one: {offset_defs}. Of these, `scripts/alignment_defect_ci.py:{X8_['adc']}` `rollout(…, offset)` "
       f"is the one Appendix V's figures go through (`alignment_by_horizon.py` and `action_sensitivity.py` reach it).\n",
       "| Evaluator | Entry point | Accepts an offset? | How its rollout reads actions |", "|---|---|---|---|",
       f"| the sweep (M-74; `results/mn_sweep_eval.json`) | `{MSE}:{X8_['score']}` `score(model, data, cfg, scale, starts, m, m_max)` | "
       f"no: `action_offset=1` is hard-coded at `:{X8_['score_off']}` | `RWMEnsemble.rollout` at offset 1: causal |",
       f"| the baselines (M-75, M-76; `results/baselines_eval.json`) | `{BLE}:{X8_['eval']}` `evaluate(queued, runs, results, iters, out_path, …)` | "
       f"no: it scores through the sweep's `score` (offset 1), and the baseline models assert offset 1 "
       f"(`src/baselines/common.py:{X8_['c_ass']}`, `src/baselines/rssm.py:{X8_['r_ass']}`) | the MLP and transformer read the block of rows "
       f"`action_rows_for(i, history)` = i − history + 1 … i (`src/baselines/common.py:{X8_['arf']}`); the RSSM steps with `action[:, t]` "
       f"to predict state t (`src/baselines/rssm.py:{X8_['r_tr']}`): causal |",
       f"| the A/B comparison (M-23 and §5's by-horizon table) | `{A1S}:{X8_['a1']}` `rel_l1_per_traj(model, starts, hs)`; "
       f"`scripts/task_d1_threeseed.py:{X8_['d1']}` `per_traj`; `scripts/task5_analyse.py:{X8_['t5']}` `traj` | no: offset 1 is hard-coded at "
       f"`a1_ab_by_horizon.py:{X8_['a1_off']}`, `task_d1_threeseed.py:{X8_['d1_off']}` and `task5_analyse.py:{X8_['t5_off']}` | "
       f"`RWMEnsemble.rollout` at offset 1: causal |",
       "",
       "None of the three accepts an offset, so X8 adds one to each, defaulting to today's behaviour, as Annex 2 X8 provides. For the "
       "baselines that also means relaxing their `assert action_offset == 1` and defining offset 0 for a model that reads a block of "
       "action rows rather than one.\n",
       "**PF8: PASS** (recorded: no evaluator takes an offset).\n"]
verdicts["PF8"] = True

# ================================================================ PF9 disk and memory
du = shutil.disk_usage(".")
mem = int(subprocess.run(["sysctl", "-n", "hw.memsize"], capture_output=True, text=True).stdout)
size = lambda d: sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(d) for f in fs)
arm = max(size(f"runs/arm{a}_seed{s}") for a in "AB" for s in (0, 1, 2))
arm_json = max(os.path.getsize(f"results/step5_arm{a}_seed{s}.json") for a in "AB" for s in (0, 1, 2))
arm_rep = max(os.path.getsize(f"results/step5_arm{a}_seed{s}_report.txt") for a in "AB" for s in (0, 1, 2)
              if os.path.exists(f"results/step5_arm{a}_seed{s}_report.txt"))
qlog = max(os.path.getsize(os.path.join("runs/queue_logs", f)) for f in os.listdir("runs/queue_logs"))
blsz = {a: max(size(f"runs/baseline_{a}_ar_s7_seed{s}") for s in (0, 1, 2)) for a in ("mlp", "transformer")}
s7n = {a: bv[f"{a}_s7"]["n_params"] for a in ("mlp", "transformer")}
bl_est = {a: blsz[a] * counts[a] / s7n[a] for a in blsz}
bl_json = max(os.path.getsize(os.path.join("results", f)) for f in os.listdir("results") if f.startswith("baseline_run_") and "_ar_" in f)
n3 = 24
est = n3 * (arm + arm_json + arm_rep + qlog) + sum(3 * (bl_est[a] + bl_json + qlog) for a in bl_est)
MB = 1 / (1 << 20)
md += ["## PF9 — disk and memory\n",
       f"- Free disk on the repository's volume: {du.free / (1 << 30):.1f} GiB of {du.total / (1 << 30):.1f} GiB "
       f"({100 * du.used / du.total:.0f}% used). RAM: {mem / (1 << 30):.0f} GiB (`sysctl hw.memsize`), so one training job at a time (§1.5).",
       "- Estimate for the 30 new runs, from the largest existing run of each kind:",
       f"  - X3, {n3} Arm A/B runs at 2,500 iterations: {arm * MB:.1f} MiB of checkpoints each (`runs/arm*_seed*`), a "
       f"{arm_json * MB:.2f} MiB run record, a {arm_rep / 1024:.0f} KiB report and a {qlog / 1024:.0f} KiB queue log;",
       f"  - X4, 6 matched baselines: the Table S7 runs' checkpoints scaled by parameter count (MLP {blsz['mlp'] * MB:.1f} MiB × "
       f"{counts['mlp']:,}/{s7n['mlp']:,} ≈ {bl_est['mlp'] * MB:.1f} MiB; transformer {blsz['transformer'] * MB:.1f} MiB × "
       f"{counts['transformer']:,}/{s7n['transformer']:,} ≈ {bl_est['transformer'] * MB:.1f} MiB), plus a {bl_json * MB:.2f} MiB run record each;",
       f"  - in all about **{est / (1 << 30):.2f} GiB**, {100 * est / du.free:.1f}% of the free space.\n"]
p9 = est < 0.5 * du.free
verdicts["PF9"] = p9
md.append(f"**PF9: {'PASS' if p9 else 'FAIL'}.**\n")

# ================================================================ summary
summ = ["## Summary\n", "| Check | Result |", "|---|---|"]
summ += [f"| {k} | {'recorded (records only)' if v is None else ('PASS' if v else '**FAIL**')} |" for k, v in verdicts.items()]
md[2:2] = summ + [""]
open(OUT, "w").write("\n".join(md) + "\n")
print("wrote", OUT, verdicts)
