"""T0 item 4: the round-2 baselines, written to docs/presubmission/round2/BASELINE_T0.md.

One fast build (FILE_MAP §3), then every gate, then S0's two extra gates (part_f_gate with the identity
configured and no clone, and submission_check), each recorded as exit code plus its summary line. Then
the body word counts by FILE_MAP §13's rule (whitespace tokens, str.split()) and the page count. Every
figure is read from what the scripts print or from PAPER.md; none is typed. Tracked files that a gate
rewrites as a side effect (PAPER.pdf's timestamps, results/part_f_gate.json) are restored afterwards, as
S0 did, and the tree is asserted unchanged. Logs go to $T0_LOGS (outside the repository).
Run from the repository root:  $PY docs/presubmission/round2/t0_baseline.py
"""
import os, re, subprocess, sys, json, datetime

PY = sys.executable
LOGS = os.environ.get("T0_LOGS", "/Users/Shared/rwm_verify/evidence/R2T0")
os.makedirs(LOGS, exist_ok=True)
OUT = "docs/presubmission/round2/BASELINE_T0.md"


def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True).stdout.rstrip("\n")  # keep porcelain's leading column


def run(name, cmd, env=None, rx=None):
    p = subprocess.run(cmd, capture_output=True, text=True, env={**os.environ, "PY": PY, **(env or {})})
    open(os.path.join(LOGS, name + ".log"), "w").write(p.stdout + p.stderr)
    lines = [l.strip() for l in (p.stdout + p.stderr).splitlines() if l.strip()]
    summ = [l for l in lines if re.search(rx or r"\bPASS\b|\bFAIL|RESULT|criteria met|checks pass|corruptions caught|wrote (PAPER|MODEL|README)", l)]
    if rx: summ = summ[:3]
    return p.returncode, ("; ".join(summ) if rx else (summ[-1] if summ else (lines[-1] if lines else "")))[:300]


status_before = git("status", "--porcelain", "--untracked-files=all")
head = git("rev-parse", "--short", "HEAD")
rows = []
for s in ("paper_numbers", "build_paper", "build_model_card", "build_readme", "compile_paper"):
    rows.append(("fast build", s + ".py", *run("build_" + s, [PY, f"scripts/{s}.py"])))
compile_log = open(os.path.join(LOGS, "build_compile_paper.log")).read()
GATES = [("ledger_check.py", [], r"RESULT"), ("check_comparative_claims.py", ["--self-test"], r"claims verified|corruptions caught"),
         ("typed_numeral_audit.py", [], r"self-test|typed numerals in|unclassified"), ("restatement_index.py", [], r"\bPASS\b|\bFAIL|typed restatements|ambiguous"),
         ("horizon_sweep.py", [], r"findings"), ("xref_sweep.py", [], r"^\s*(TOTAL|total)|suspect"), ("check_scope_audit.py", [], r"kinds \d+"),
         ("pdf_render_check.py", [], r"PASS")]
for g, a, rx in GATES:
    rows.append(("gate", " ".join([g] + a), *run("gate_" + g[:-3], [PY, f"scripts/{g}", *a], rx=rx)))
name, mail = git("log", "-1", "--format=%an"), git("log", "-1", "--format=%ae")
url = git("remote", "get-url", "origin")
handle = re.sub(r".*github.com[:/]([^/]+)/.*", r"\1", url)
repo_url = re.sub(r"\.git$", "", re.sub(r"^(https://|git@)", "", url).replace(":", "/", 1))
rows.append(("S0 extra", "part_f_gate.py (identity configured, no CLONE_RESULTS)",
             *run("gate_part_f_gate", [PY, "scripts/part_f_gate.py"], {"RWM_IDENT": f"{name},{mail},{handle}", "RWM_IDENT_REPO": repo_url})))
rows.append(("S0 extra", "submission_check.py", *run("gate_submission_check", [PY, "scripts/submission_check.py"])))

# restore what the gates rewrote as side effects, then assert the tree is as it was
changed = [l[3:] for l in git("status", "--porcelain").splitlines()]
restored = [f for f in changed if f in ("PAPER.pdf", "results/part_f_gate.json")]
if restored:
    subprocess.run(["git", "checkout", "--", *restored], check=True)
status_after = git("status", "--porcelain", "--untracked-files=all")

# body words, FILE_MAP §13
L = open("PAPER.md", encoding="utf-8").read().split("\n")
idx = lambda rx: next(i for i, l in enumerate(L) if re.match(rx, l))
s, d, e = idx(r"^## 1\. Introduction\s*$"), idx(r"^## Data and code\s*$"), idx(r"^## References\s*$")
words = lambda a, b: sum(len(l.split()) for l in L[a:b])
heads = [(i, l) for i, l in enumerate(L) if re.match(r"^#{2,3} ", l)]
sections = []
for k, (i, l) in enumerate(heads):
    j = heads[k + 1][0] if k + 1 < len(heads) else len(L)
    sections.append((l.strip(), i + 1, words(i, j)))
pages = re.search(r"\((\d+) pages", compile_log)

md = [f"# Round-2 baseline (T0)\n",
      f"Recorded {datetime.date.today().isoformat()} by session T0 on branch `presubmission2` at `{head}` "
      f"(= `pre-round2`, round 1's final commit, plus T0's own commits, which touch only `docs/presubmission/round2/`). "
      f"Generated by `docs/presubmission/round2/t0_baseline.py`; logs outside the repository.\n",
      "## Length\n",
      "Body by FILE_MAP §13's rule (whitespace tokens), from `## 1. Introduction`:\n",
      "| Cut-point | Words |", "|---|---:|",
      f"| to \"Data and code\" (the line before `## Data and code`; ruling U3's measure) | {words(s, d):,} |",
      f"| to \"References\" (the line before `## References`; FILE_MAP §13's original command) | {words(s, e):,} |",
      f"| whole `PAPER.md` | {words(0, len(L)):,} |",
      f"\nU3's target: at most 19,000 to \"Data and code\".\n",
      f"**Pages:** {pages.group(1) if pages else 'NOT FOUND'} (`compile_paper.py`).\n",
      "### Per section (`##` and `###` headings of `PAPER.md`, heading line to the line before the next heading)\n",
      "| Heading | PAPER.md line | Words |", "|---|---:|---:|"]
md += [f"| {h.replace('|', '/')} | {ln} | {w:,} |" for h, ln, w in sections]
md += ["\n## Gates after one fast build\n",
       "| Kind | Script | Exit | Summary line |", "|---|---|---:|---|"]
md += [f"| {k} | `{n}` | {rc} | {sm.replace('|', '/')} |" for k, n, rc, sm in rows]
md += [f"\nRestored after the gates (side effects, as at S0): {', '.join('`'+r+'`' for r in restored) or 'none'}. "
       f"Working tree unchanged by the run: {'yes' if status_before == status_after else 'NO'}.\n"]
open(OUT, "w").write("\n".join(md) + "\n")
print(f"wrote {OUT}: body {words(s, d)} to Data and code, {words(s, e)} to References, pages {pages.group(1) if pages else '?'}; "
      f"tree unchanged {status_before == status_after}")
for r in rows: print(r[0], "|", r[1], "| rc", r[2], "|", r[3])
