"""T0 item 5: the preflight assertions P1-P4 (round2/PLAN.md §2 T0), written to round2/PREFLIGHT.md.

Reads only: weights under runs/, results/*.json, docs/presubmission/s8_cpu_jobs.json and RUN_QUEUE.md,
file modification times of the timing-probe runs, and the dataset (to re-derive one evaluator's start rows
with its own function). Writes nothing else. Any failed assertion is recorded as FAIL; the session then
stops BLOCKED (PLAN.md T0 item 5). Run from the repository root with the project interpreter.
"""
import datetime, glob, hashlib, json, os, re, sys

sys.path.insert(0, "src"); sys.path.insert(0, "scripts")
OUT = "docs/presubmission/round2/PREFLIGHT.md"
md, verdicts = ["# Round-2 preflight (T0 item 5)\n",
                "Generated by `docs/presubmission/round2/t0_preflight.py`. Each assertion is PASS or FAIL; any FAIL stops T0 BLOCKED.\n"], {}


def J(p):
    return json.load(open(p))


# ---------------------------------------------------------------- P1 weights
need = [f"runs/armA_seed{s}_10k/weights_{i}.pt" for s in (0, 1, 2) for i in (2500, 5000, 7500, 10000)]
mn_cfgs = sorted({re.sub(r"_seed\d$", "", os.path.basename(d)) for d in glob.glob("runs/mn_M*_N*_seed[012]")})
need += [f"runs/{c}_seed{s}/weights_2500.pt" for c in mn_cfgs for s in (0, 1, 2)]
bl_fams = sorted({re.sub(r"_s7_seed\d$", "", os.path.basename(d)) for d in glob.glob("runs/baseline_*_s7_seed[012]")})
need += [f"runs/{f}_s7_seed{s}/weights_2500.pt" for f in bl_fams for s in (0, 1, 2)]
need += [f"runs/armA_seed{s}/weights_2500.pt" for s in (0, 1, 2)]
missing = [p for p in need if not (os.path.isfile(p) and os.path.getsize(p) > 0)]
setup = open("setup.sh").read()
ck_sha = re.search(r'CKPT_SHA256="([0-9a-f]{64})"', setup).group(1)
ck = os.path.join("..", "robotic_world_model_lite", "assets", "models", "pretrain_rnn_ens.pt")
ck_ok = os.path.isfile(ck) and hashlib.sha256(open(ck, "rb").read()).hexdigest() == ck_sha
p1 = (not missing) and len(mn_cfgs) == 8 and len(bl_fams) == 6 and ck_ok
verdicts["P1"] = p1
md += ["## P1 — the weights exist\n",
       f"- Arm A 10k runs, seeds 0-2 at 2,500/5,000/7,500/10,000: {sum(1 for p in need[:12] if p not in missing)}/12 present.",
       f"- M/N sweep configs found: {len(mn_cfgs)} ({', '.join(mn_cfgs)}); weights_2500 for seeds 0-2: {sum(1 for p in need if p.startswith('runs/mn_') and p not in missing)}/{3*len(mn_cfgs)} present.",
       f"- Baseline families (Table S7 builds): {len(bl_fams)} ({', '.join(bl_fams)}); weights_2500 for seeds 0-2: {sum(1 for p in need if p.startswith('runs/baseline_') and p not in missing)}/{3*len(bl_fams)} present.",
       f"- Arm A (2,500-iteration runs), seeds 0-2: {sum(1 for p in need[-3:] if p not in missing)}/3 present.",
       f"- The released checkpoint (`setup.sh`'s target, `../robotic_world_model_lite/assets/models/pretrain_rnn_ens.pt`): "
       f"{'present, SHA-256 equals setup.sh' + chr(39) + 's CKPT_SHA256' if ck_ok else 'MISSING or SHA-256 MISMATCH'}.",
       f"- Missing or empty: {missing or 'none'}.",
       f"\n**P1: {'PASS' if p1 else 'FAIL'}.**\n"]

# ---------------------------------------------------------------- P2 arena identity
import rwm_data as R, rollout_eval as E, rwm_metrics as MET  # noqa: E402
paths = R.repo_paths()
R.CFG = R.load_reference_config(paths["lite"])
R.DATA, ep = R.load_data(paths["csv"], verbose=False)
split = E.make_split(seed=0, strat_path=os.path.join(R.RESULTS, "step0_strat.json"), verbose=False)
a1_starts = MET.non_overlapping_starts(ep, list(split["holdout_episodes"]), 400)
a1 = J("results/a1_ab_by_horizon.json")["design"]
h2h = J("results/head_to_head_accuracy.json")
mn = J("results/mn_sweep_eval.json")["arenas"]["held_out"]
bl = J("results/baselines_eval.json")["arenas"]["held_out"]
rows = {
    "§5 by-horizon table (`a1_ab_by_horizon.json`; starts re-derived by its own `non_overlapping_starts(ep, holdout_episodes, 400)`)":
        (a1_starts, f"episodes {a1['episodes']}, {a1['n_trajectories']} x {a1['traj_len']} steps, START_STEP = {E.START_STEP}"),
    "head-to-head table (`head_to_head_accuracy.json` `traj_start_row`)":
        (h2h["traj_start_row"], f"episodes {h2h['arena_episodes']}, start_step {h2h['start_step']}, n_forecast_steps {h2h['n_forecast_steps']}"),
    "sweep evaluator (`mn_sweep_eval.json` arenas.held_out.starts)":
        (mn["starts"], f"episodes {mn['episodes']}, forecast rows {mn['forecast_rows']}"),
    "baseline evaluator (`baselines_eval.json` arenas.held_out.starts)":
        (bl["starts"], f"episodes {bl['episodes']}, forecast rows {bl['forecast_rows']}"),
}
ref = list(map(int, h2h["traj_start_row"]))
p2 = all(list(map(int, s)) == ref for s, _ in rows.values()) and len(ref) == 4
verdicts["P2"] = p2
md += ["## P2 — arena identity of the four held-out 400-step trajectories\n",
       "| Artifact | Start rows | Window convention |", "|---|---|---|"]
md += [f"| {k} | {list(map(int, s))} | {w} |" for k, (s, w) in rows.items()]
md += [f"\nAll four name the same {len(ref)} start rows {ref}: **P2: {'PASS' if p2 else 'FAIL'}.** "
       "(The forecast windows agree too: 32 history rows, then forecast rows start+32 to start+399, i.e. 368 steps.)\n"]

# ---------------------------------------------------------------- P3 uncontended timing probes
tz = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
launch_m = re.search(r"on (\d{4}-\d{2}-\d{2}) at (\d{2}:\d{2}:\d{2})", open("docs/presubmission/RUN_QUEUE.md").read())
launch = datetime.datetime.fromisoformat(f"{launch_m.group(1)}T{launch_m.group(2)}").replace(tzinfo=tz)
T = J("results/mn_sweep_timing.json")
art = {f"M{c['M']}_N{c['N']}": c["steady_s_per_iter"] for c in T["configs"]}
art["M32_N8"] = T["calibration"]["centre_probe"]["steady_s_per_iter"]
probe = {}
for f in glob.glob("runs/timing_probe/mn_sweep_run_*_seed0.json"):
    k = os.path.basename(f)[len("mn_sweep_run_"):-len("_seed0.json")]
    end = datetime.datetime.fromtimestamp(os.path.getmtime(f), tz)
    d = J(f)
    start = end - datetime.timedelta(seconds=float(d["wall_clock_s"]))
    probe[k] = (start, end, d["s_per_iter"])
jobs = J("docs/presubmission/s8_cpu_jobs.json")["jobs"]
pw_start, pw_end = min(v[0] for v in probe.values()), max(v[1] for v in probe.values())
timed = [j for j in jobs if isinstance(j.get("start"), str) and isinstance(j.get("end"), str)]
untimed = [j for j in jobs if j not in timed]
overl = [j for j in timed if datetime.datetime.fromisoformat(j["start"]) < pw_end and datetime.datetime.fromisoformat(j["end"]) > pw_start]
# An untimed job is bounded by its session: sessions ran strictly in order (start gate), so a job of
# session SX began after the previous session's last commit. Bound each by that commit time.
import subprocess
def last_commit_of(tag):
    out = subprocess.run(["git", "log", "-1", "--format=%cI", f"--grep=^\\[{tag}\\]"], capture_output=True, text=True).stdout.strip()
    return datetime.datetime.fromisoformat(out) if out else None
PREV = {"S2b": "S2a", "S3": "S2b", "S4": "S3", "S5": "S4", "S6": "S5", "S7": "S6", "S8": "S7"}
untimed_bound = []
for j in untimed:
    sess = j["job"].split()[0]
    b = last_commit_of(PREV[sess]) if sess in PREV else None
    untimed_bound.append((j["job"][:60], sess, b, b is not None and b > pw_end))
match = {k: (art.get(k), probe.get(k, (None, None, None))[2]) for k in sorted(art)}
same_run = all(v[1] is not None and abs(v[0] - v[1]) / v[0] < 0.05 for v in match.values())
p3 = pw_end < launch and not overl and same_run and set(probe) == set(art) and all(ok for *_, ok in untimed_bound)
verdicts["P3"] = p3
md += ["## P3 — the M/N timing probes were uncontended\n",
       f"- The committed `results/mn_sweep_timing.json` is the re-probe `mn_sweep_timing.py --write-queue` ran just before the launch "
       f"(commit ae7a7fe; the earlier 2097c9b probe was superseded). Its per-config `steady_s_per_iter` agrees within 5% with the on-disk "
       f"probe runs in `runs/timing_probe/` (mean `s_per_iter`, warm-up included): {'yes' if same_run else 'NO'}.",
       f"- Probe window, from each run's file time minus its `wall_clock_s`: {pw_start:%Y-%m-%d %H:%M:%S} to {pw_end:%H:%M:%S} (+05:30).",
       f"- Queue launch (`RUN_QUEUE.md`): {launch:%Y-%m-%d %H:%M:%S}. The probes end {(launch - pw_end).total_seconds():.0f} s before it.",
       f"- Logged CPU jobs (`s8_cpu_jobs.json`, {len(timed)} with times) overlapping the probe window: {len(overl)} {[j['job'] for j in overl] or ''}",
       f"- Jobs logged without times: {len(untimed)}. " + "; ".join(f"'{n}...' belongs to {s}, which began after the previous session's last commit, {b:%Y-%m-%d %H:%M:%S}: {'after' if ok else 'NOT after'} the probe window" for n, s, b, ok in untimed_bound),
       "\n| Config | committed steady s/iter | on-disk probe s/iter | probe start | probe end |", "|---|---:|---:|---|---|"]
md += [f"| {k} | {art[k]:.4f} | {probe[k][2]:.4f} | {probe[k][0]:%H:%M:%S} | {probe[k][1]:%H:%M:%S} |" for k in sorted(art) if k in probe]
md += [f"\nContended probes: {'none' if p3 else 'see above'}. **P3: {'PASS' if p3 else 'FAIL'}.** "
       "(The six baseline-family probes, `runs/baselines_probe/`, ran 18:48-19:00 against the running queue, as round 1 logged; "
       "PLAN N3 re-probes them. They are not part of P3.)\n"]

# ---------------------------------------------------------------- P4 the M-23 seed-1 values
g = J("results/task5_analysis.json")["gaps"]["out-of-sample|10000|h368"]
num = {k: v for k, v in g.items() if isinstance(v, (int, float))}
want = {"A": 0.3509, "B": 1.5540, "gap": 1.2033, "lo": 0.5606, "hi": 2.0467}
def find(*names):
    for n in names:
        if n in g: return g[n]
    return None
got = {"A": find("A", "mean_A", "A_mean", "a"), "B": find("B", "mean_B", "B_mean", "b"), "gap": find("gap", "mean_gap", "diff"),
       "lo": find("ci_lo", "lo", "lower"), "hi": find("ci_hi", "hi", "upper")}
ci = find("ci", "ci95", "interval")
if (got["lo"] is None or got["hi"] is None) and isinstance(ci, (list, tuple)) and len(ci) == 2:
    got["lo"], got["hi"] = ci
p4 = all(got[k] is not None and round(float(got[k]), 4) == want[k] for k in want)
verdicts["P4"] = p4
md += ["## P4 — the M-23 rule's seed-1 values\n",
       f"`results/task5_analysis.json` → `gaps[\"out-of-sample|10000|h368\"]` (fields: {sorted(g)}):\n",
       "| Quantity | PLAN says | Artifact (4 d.p.) |", "|---|---:|---:|"]
md += [f"| {k} | {want[k]} | {round(float(got[k]), 4) if got[k] is not None else 'NOT FOUND'} |" for k in want]
md += [f"\n**P4: {'PASS' if p4 else 'FAIL'}.**\n",
       "## Summary\n", " ".join(f"{k}: {'PASS' if v else 'FAIL'}." for k, v in verdicts.items())]
open(OUT, "w").write("\n".join(md) + "\n")
print(" ".join(f"{k}={'PASS' if v else 'FAIL'}" for k, v in verdicts.items()))
sys.exit(0 if all(verdicts.values()) else 1)
