"""
C3 -- one printable file the C1 review is done from. No session state, no tool.

WHAT THIS REPLACES. The plan was an interactive expectation-then-reveal session
tool. It is not built and it will not be: it is scope creep on a gate a person
clears by reading, and a session tool adds state that has to be trusted. This
produces a single static document instead. One claim per row, printable, readable
on a train, with no dependency on anything still running.

THE TIERING, and why it is not the existing one. `c1_preflags.py` sorts by what
changed and by which commit touched it. Neither of the two confirmed defects
would have surfaced near the top: appendix D is old text nobody expected to move,
and §5's table is new. Both sentences PREDATE the revision that made them wrong,
which is a property of the git history and is what `c2_revision_cohorts.py`
measures. So:

  Tier 0  the sentence is older than a revision that moved the quantity it talks
          about -- the h = 100 grid, or §5's move to three seeds. Evidence-based:
          this is where both confirmed defects sat.
  Tier 1+ the existing tiers, unchanged, underneath.

Tier 0 CUTS ACROSS the others: a claim can be Tier 0 and Tier 3. It is listed
once, in Tier 0, with its original tier shown.

WHAT EACH ROW CARRIES. Section, tier, the reason it is in that tier, the current
text, the last human-approved text where one exists, what changed between them,
the resolved value of every key, and the advisory flags. The reviewer needs
nothing else open.

THE STOPPING RULE for the second pass is written into the file itself, above the
first claim, because the brief requires it to exist before the first pass starts
and a rule written afterwards is not a rule.

Writes docs/C1_REVIEW_CHECKLIST.md.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, "src"))
import rwm_data as R  # noqa: E402

OUT = os.path.join("docs", "C1_REVIEW_CHECKLIST.md")


def main():
    Q = json.load(open(os.path.join(R.RESULTS, "c1_review_queue.json")))
    C = json.load(open(os.path.join(R.RESULTS, "revision_cohorts.json")))
    N = json.load(open(os.path.join(R.RESULTS, "paper_numbers.json")))
    RI = json.load(open(os.path.join(R.RESULTS, "restatement_index.json")))

    # A claim is Tier 0 if the paragraph it sits in overlaps a stale sentence.
    stale_lines = {r["line"] for r in C["tier0"]}
    stale_by_line = {r["line"]: r for r in C["tier0"]}
    for c in Q["claims"]:
        pl = int(c.get("paragraph_line") or 0)
        hit = [ln for ln in stale_lines if 0 <= ln - pl < 12]
        c["tier0"] = bool(hit)
        c["tier0_line"] = min(hit) if hit else None
        c["tier0_cohorts"] = (stale_by_line[min(hit)]["stale_for"] if hit else [])

    t0 = [c for c in Q["claims"] if c["tier0"]]
    rest = [c for c in Q["claims"] if not c["tier0"]]
    rest.sort(key=lambda c: (c["tier"], c["section"]))

    # Same-quantity candidates from the restatement index: pairs of keys that
    # agree today and would not have to. The reviewer sees them beside the claims.
    same_q = [x for x in RI["restatements"] if x["same_quantity_candidate"]]

    L = []
    n_claims = len(Q["claims"])
    L.append(f"# C1 review checklist — {n_claims} claims, one row each\n")
    L.append("**Generated by `scripts/c3_review_checklist.py`. Do not hand-edit.** "
             "Regenerate after any change to `PAPER.template.md`.\n")
    L.append("This is the whole review. There is no session tool and no script that "
             "records a verdict: the gate is cleared by a person reading, and a "
             "clearing mechanism a script can drive is not a gate.\n")

    L.append("## Before the first pass\n")
    # Both figures derived. They were typed as "89 claims" and "six hours" when
    # this generator was written, and the revision more than doubled the queue --
    # every rewritten sentence correctly drops its verdict -- so the file told a
    # reviewer to budget six hours for 191 claims while calling them 89. A
    # generator with a typed count is the defect it was written to prevent.
    _hours = max(6, round(n_claims * 2.5 / 60))
    L.append(f"**Budget.** About {_hours} hours. {n_claims} claims at two and a half "
             f"minutes each is optimistic, and the Tier 1 claims in §5 are the "
             f"slowest in the document. The queue grew from 89 to {n_claims} during "
             f"the revision-3 pass: `task_c1_claims_audit.py` drops a claim's verdict "
             f"when its wording changes, and that pass rewrote the abstract, §4, §5, "
             f"§6.2, §6.3, §6.7, §7.5 and §11 and added three appendices.\n")
    L.append("**The stopping rule for the second pass, written before the first "
             "pass starts.**\n")
    L.append("A second pass happens if, and only if, the first pass ends with either:\n")
    L.append("- **any claim rejected or amended**, in which case the second pass covers "
             "every claim sharing a key with the amended one, plus every claim in the "
             "same section; or\n")
    L.append("- **three or more claims deferred** as \"cannot judge without checking "
             "the artifact\", in which case the second pass covers the deferred set only.\n")
    L.append("If neither holds, there is no second pass. The reason for fixing this now "
             "is that a stopping rule chosen after seeing the results is chosen to stop, "
             "and this project has a rule (`S-12`) it had to withdraw for exactly that.\n")
    L.append("**A claim is not approved by being unflagged.** The flags say where to "
             "slow down. Every row needs a yes.\n")

    L.append("## How the tiers were chosen\n")
    L.append(f"Tier 0 is **{len(t0)} claims** whose paragraph contains a sentence older "
             f"than a revision that moved the quantity it talks about. The cohorts:\n")
    for co in C["cohorts"]:
        L.append(f"- **{co['label']}** — `{co['short']}`, {co['subject']}. {co['why']}\n")
    L.append(f"\nOf {C['n_sentences']} sentences in the template, {C['n_tier0']} predate "
             f"at least one of those, and {C['n_tier0_with_values']} of those carry a "
             f"substituted value.\n")
    L.append("The existing tiering — by section and by newness — would have put neither "
             "confirmed defect near the top: Appendix D is old text nobody expected to "
             "move, and §5's table is new. Both sentences predate the revision that made "
             "them wrong. That is why this tier exists and why it goes first.\n")

    L.append("## Same-quantity candidates, to read before Tier 0\n")
    L.append(f"{len(same_q)} values are printed in more than one place from more than one "
             f"key. None is wrong today. Each is the question **\"are these two keys the "
             f"same quantity?\"** — and where the answer is yes, the pair is one revision "
             f"away from B1, which is exactly the state §5 was in before one of its two "
             f"floor ratios moved to three seeds and the other did not.\n")
    L.append("| value | keys | places |\n|---|---|---|\n")
    for x in sorted(same_q, key=lambda z: -z["n_locations"])[:20]:
        secs = sorted({l["section"][:34] for l in x["locations"]})
        L.append(f"| `{x['value']}` | {', '.join('`%s`' % k for k in x['keys'])} | "
                 f"{'; '.join(secs)} |\n")
    L.append("\n")

    def render(c, n, tier_label):
        L.append(f"### {n}. §{c['section']} — Tier {tier_label}\n")
        why = c["tier_reason"]
        if c["tier0"]:
            why = (f"paragraph contains a sentence predating "
                   f"{', '.join(c['tier0_cohorts'])} (template line {c['tier0_line']}); "
                   f"original tier {c['tier']} — {why}")
        L.append(f"*{why}*\n")
        L.append(f"**Now.** {c['claim']}\n")
        prev = c.get("previous_text")
        if prev and prev != "None":
            L.append(f"**Last approved.** {prev}\n")
        else:
            L.append("**Last approved.** — (new, or no approved text on record)\n")
        keys = c["keys"] if isinstance(c["keys"], list) else eval(c["keys"])
        if keys:
            L.append("\n| key | value | artifact |\n|---|---|---|\n")
            for k in keys:
                if k in N:
                    L.append(f"| `{k}` | {N[k]['value']} | `{N[k]['source']}` |\n")
        flags = c["flags"] if isinstance(c["flags"], list) else eval(c["flags"])
        L.append(f"\n**Flags.** {', '.join('`%s`' % f for f in flags) if flags else 'none'}\n")
        L.append("\n**Verdict** ☐ approve  ☐ amend  ☐ reject  ☐ defer   "
                 "**Reviewer** ______  **Date** ______\n\n---\n\n")

    L.append(f"## Tier 0 — {len(t0)} claims\n\n")
    for n, c in enumerate(sorted(t0, key=lambda c: c["section"]), 1):
        render(c, n, "0")
    L.append(f"## Tiers 1–4 — {len(rest)} claims\n\n")
    for n, c in enumerate(rest, len(t0) + 1):
        render(c, n, c["tier"])

    os.makedirs("docs", exist_ok=True)
    open(OUT, "w").write("".join(L))
    print("C3 — C1 REVIEW CHECKLIST")
    print("=" * 80)
    print(f"  claims           : {len(Q['claims'])}")
    print(f"  Tier 0           : {len(t0)}  (revision cohorts, read first)")
    print(f"  Tiers 1-4        : {len(rest)}")
    print(f"  same-quantity candidates listed: {len(same_q)}")
    print(f"  stopping rule for the second pass: written above the first claim")
    print(f"  wrote {OUT} ({len(''.join(L).splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
